### ISSUE TITLE
Contextify error and "Uncaught (in promise) Error" when I start Kaku and try to play

### ISSUE THREAD

**Issue by distriker** [EragonJ/Kaku#116]
Hi, yesterday I have notice of Kaku and I decided try it. But, it is giving me some errors when I execute the program and try to play.

First of all, on the setup environment step I have a problem with **npm install**: contextify [gives me an error](https://gist.github.com/distriker/e6ed86b8bda783d68876) and didn't install. I have read that on Windows *contextify* gives some error for Python Environment Variable, but I have installed Python and in the console I set it to the correct file: C:\Python34\python.exe.

Then, if I try to execute Kaku without it with **electron .** in the main folder, the interface is rendered but I can't play any track. You can [see the error](https://gist.github.com/distriker/d7f0c71f8e9ba5f5f188) that show me the console.

I really want to try Kaku, so I hope that you can help me.

Regards, *Iván*

**Comment by EragonJ** [comment]
I think this might be another issue that I found long time ago. But sadly, I have no windows to test the environment, hope someone can help on this part or hope I can get windows to test with later.

**Comment by distriker** [comment]
It's a shame, sincerely. I hope that the bug will be found soon! If I could, I would help you in that.

Good luck!

Regards, *Iván*

**Comment by EragonJ** [comment]
Well, I think this may be problems on your side. I borrowed a Windows 8.1 desktop and everything works perfect (all functionalities work perfect), this is the screenshot from my side : http://imgur.com/nzJf7gR

checked from your error log : 
```bash
[10760:0701/012758:INFO:CONSOLE(365)] "Uncaught (in promise) undefined", source: node.js (365)
```
Maybe the problem but this doesn't happen on my side, please make sure everything is latest and youtube-dl does install correctly (with python >= 2.7). Feel free to re-open if you find any way to solve this or something else. 

Thanks.

**Comment by EragonJ** [comment]
And also, please make sure you did follow the instructor (https://github.com/EragonJ/Kaku#prerequistiques) here.

**Comment by EragonJ** [comment]
I think the problem is because `youtube-dl` is python based and your $PATH is wrong so that it can't be executed correctly. Just an assumption.

**Comment by EragonJ** [comment]
Yes, after digging it deeper, it is all about `python` which may be absent in your $PATH, please double check before using `electron .` to make it work, thanks.

**Comment by distriker** [comment]
Finally, after verify that I had set correctly the Python executable path I have read on node-gyp repository that it don't support Python 3.x.x. I have installed Python 2.7, set again the variable and now this error dissapear. Perfect! Python problem fixed! I think that you should specify that in the requirements.

But... node-gyp requires more... Now it says me that:
`MSBUILD : error MSB3428: No se pudo cargar el componente "VCBuild.exe" de Visual C++. Para corregir este problema, 1) instale .NET Framework 2.0 SDK, 2) instale Microsoft Visual Studio 2005 o 3) agregue la ubicación del componente a la ruta de acceso del sistema si está instalado en otro lugar.  [S:\kaku\node_modules\mock-browser\node_modules\node-jsdom\node_modules\contextify\build\binding.sln]`

I am installing Visual Studio Express 2013... One question: I don't want to develop anything of Kaku (in any case, I will translate to spanish), is all this necessary for a user that want to use Kaku?

Regards, *Iván*

**Comment by EragonJ** [comment]
Right now this application is still not user-friendly for windows users, maybe in the future this can be fixed  if there is anyone who is good at programming and using windows, but sadly for now, I only have my MacOS, I think the better way for now is to support Mac & Linux officially only. 

No matter how, still thanks for trying to provide a translation for Spanish if possible.

**Comment by distriker** [comment]
Don't worry EragonJ, I understand it. Windows is so... hard to test and develop...

I already have the translation for Spanish. I'm going to make the Pull Request.
