### ISSUE TITLE
When I ctrl+m to minimize I get an error

### ISSUE THREAD

**Issue by mimi89999** [EragonJ/Kaku#119]
When I ctrl+m to minimize I get this error:
![capture du 2015-07-02 08 51 14](https://cloud.githubusercontent.com/assets/8530546/8470665/ab493186-2097-11e5-9575-b64c7705e9c6.png)

**Comment by EragonJ** [comment]
It would be helpful to provide a full-run test on all these submenu items and see which works on Linux while which are not. Please check bootup.js to check all predefined operations.

**Comment by mimi89999** [comment]
Only the ones in 'View' are working.

**Comment by EragonJ** [comment]
Okay, it seems that we have to dynamically construct menu items based on current environment.
