### ISSUE TITLE
Few questions about KAKU

### ISSUE THREAD

**Issue by Draxler** [EragonJ/Kaku#139]
@EragonJ 

I look at this project and it looks realy amazing, so congrats to main dev and to all who put work into this amazing app. I only have 2 questions. :) .

- Will this app be available in near future in .exe file so people could install this app into their PC?
- And, if this app be availble in English lang as well? The reson i'm asking about the language is, becuase on the screenshot KAKU is in foraign lang. 

Regards

**Comment by EragonJ** [comment]
@Draxler 

1. you can build it in Windows now, so I think they are in .exe but for me, only Linux & Mac OS are officially supported right now due to the lack of Windows to test.

2. Right now it supports English, Traditional Chinese, French and Spanish. Because I am the native speaker of Traditional Chinese and I think it would be nice to show the world that this is made in Taiwan :)

**Comment by EragonJ** [comment]
Supported languages : https://github.com/EragonJ/Kaku/blob/master/src/backend/locales/metadata.json

**Comment by EragonJ** [comment]
I think my comment above definitely answer questions you mentioned so mark as closed for now. Feel free to comment below if you have any further questions.

**Comment by Draxler** [comment]
@EragonJ
In my original post i said that KAKU is in some foraign language in your screenshot becuase i didn't know the defference between Chinese, Taiwan or any of ''these'' languges and i didn't want hurt any feelings, so i use word ''foraign'' languge instead. :smile:  
English language is good enough for me.
I think i need to wait and hope that in near future someone will made KAKU .exe install file or standalone version for Win because i don't know how.. :(
Anyway, good luck with this project.

**Comment by EragonJ** [comment]
No worries :) At least you know Taiwan now !! (wheeeee) Feel free to provide any patch if you want !

And for windows build, I'll try to make it after getting a windows device, haha.

**Comment by EragonJ** [comment]
@Draxler
