### ISSUE TITLE
Playlist ''button'' doesn't work

### ISSUE THREAD

**Issue by Draxler** [EragonJ/Kaku#159]
Win7 OS / Test version KaKu 
_______________________

Playlist button doesn't work. Nothing happens when click on it.

![123](https://cloud.githubusercontent.com/assets/7681671/8556077/ec66d2e8-24f4-11e5-9fab-5b270f646af0.PNG)

**Comment by EragonJ** [comment]
Serious ?! Can you use ctrl+alt+i to show developer tool and see whether there is any debug log or not ? I did try that yesterday.d

**Comment by Draxler** [comment]
@EragonJ 

Test version KaKu / WIN 7 /
________________________

I clicked on Playlist first (nothing happened) then i opened Console. 
If you need another fresh Console screenshot for some reason just tel me and i'll give it you.
This console was open right after i opened KaKu and clicked on Playlist. And here it is: 

![con01](https://cloud.githubusercontent.com/assets/7681671/8572577/a45b9bfc-258d-11e5-99df-2a1d59a95564.PNG)

**Comment by EragonJ** [comment]
After clicking on **add playlist** button, you should see this dialog asking for the name of the playlist, didn't you see that ?! Because from the console log, I can't see any error relates to this bug, hmmm

<img width="1172" alt="2015-07-08 11 45 40" src="https://cloud.githubusercontent.com/assets/68322/8574866/7644f180-25cb-11e5-9ded-5683b7da9bb9.png">

**Comment by Draxler** [comment]
@EragonJ 
Me to waited for this to show up but No,  nothing happens when i click on Playlist button. 
I kinda hoped Console would reveal where the problem is. :(

**Comment by EragonJ** [comment]
Can you switch to this tab and take screenshot for me ?

<img width="1078" alt="2015-07-09 11 41 10" src="https://cloud.githubusercontent.com/assets/68322/8587500/6f2e4f04-262f-11e5-9f91-c66d26f190ae.png">

**Comment by Draxler** [comment]
@EragonJ 

*Add Playlist* sudenly start working after i clicked on *Reset Database* in the Settings. :+1:  :smiley: 

![set34](https://cloud.githubusercontent.com/assets/7681671/8595028/0b6c43a0-2647-11e5-8282-4d391b85678f.PNG)

I gues this issue could be closed.

**Comment by EragonJ** [comment]
okay, marked this as closed.
