### ISSUE TITLE
I've run gulp build. Now what?

### ISSUE THREAD

**Issue by 3m0** [EragonJ/Kaku#160]
I've successfully built kaku, but it's not documented what I need to do to run it after building. I've checked the dist folder for any binaries (running on linux here) but I didn't find any. Should I run it like it's said on development with electron . or is there a binary somewhere?

**Comment by EragonJ** [comment]
`gulp build` should create a zip in your `dist/` folder, and after unzipping it, you can see the whole stuffs you need including executable Kaku. Don't you see that when entering `gulp build` ?

Or does the downloadable zip on http://kaku.rocks work ?

**Comment by 3m0** [comment]
Nope, it didn't create a zip, but it finished without any errors. Here's my gulp build output:
```
[12:32:28] Using gulpfile ~/kaku/kaku/gulpfile.js
[12:32:28] Starting 'build'...
[12:32:28] Starting 'cleanup:dist'...
[12:32:29] Finished 'cleanup:dist' after 648 ms
[12:32:29] Starting 'cleanup:build'...
[12:32:29] Finished 'cleanup:build' after 16 ms
[12:32:29] Starting '6to5:frontend'...
[12:32:39] Finished '6to5:frontend' after 9.89 s
[12:32:39] Starting '6to5:backend'...
[12:32:43] Finished '6to5:backend' after 3.98 s
[12:32:43] Starting 'linter:src'...
[12:32:47] Finished 'linter:src' after 4.03 s
[12:32:47] Starting 'copy:frontend'...
[12:32:49] Finished 'copy:frontend' after 2.44 s
[12:32:49] Starting 'copy:backend'...
[12:32:49] Finished 'copy:backend' after 41 ms
[12:32:49] Starting 'rjs'...
[12:33:12] Finished 'rjs' after 23 s
[12:33:12] Starting 'override'...
[12:33:12] Finished 'override' after 66 ms
[12:33:12] Starting 'package'...
↓ electron-v0.28.3-linux-ia32.zip [====================] 100%
[12:36:02] Finished 'package' after 2.83 min
[12:36:02] Finished 'build' after 3.57 min
```

**Comment by EragonJ** [comment]
What's your platform info !?

**Comment by EragonJ** [comment]
It's weird that you can't build it from your platform ... hmm... Can you help to debug and see what's wrong there !?

**Comment by 3m0** [comment]
Sure, what do you need me to do?

**Comment by EragonJ** [comment]
Can you try to dig into build phase and see what's going on ? it seems that you did download electron to your disk but there must be something wrong happened when wrapping all stuffs into the zip file.

**Comment by EragonJ** [comment]
And one question, does the linux build from kaku.rocks work for you ?

**Comment by mimi89999** [comment]
@EragonJ We need to build for linux-x64 ;-)

**Comment by mimi89999** [comment]
I will add that...

**Comment by mimi89999** [comment]
@3m0 Look at #170 and try to build:
gulp build --platform=linux-amd64

**Comment by mimi89999** [comment]
Could you also give the output of:
uname -a

**Comment by 3m0** [comment]
@EragonJ the buid from kaku.rocks didn't work either, but I think it's a depency problem from 32-bit libraries.
@mimi89999 this created the zip successfully, but it seems that the application is missing some css. It gives me a network error but I can connect to the internet normally (not using any proxy or anything), but this seems to be another problem. The original issue is obviously related to my 64-bit system. I'm also posting the output of uname -a, just in case:

Linux Gilgamesh 4.0.7-2-ARCH #1 SMP PREEMPT Tue Jun 30 07:50:21 UTC 2015 x86_64 GNU/Linux

**Comment by mimi89999** [comment]
@3m0 Have you added the API key?

**Comment by 3m0** [comment]
@mimi89999 Yes, I did. I can play videos normally, it's just the layout that is broken.

**Comment by mimi89999** [comment]
@3m0 In bootup.js in line 260 change 'frame': false to 'frame': true
Then: gulp && electron .
It should be OK.

**Comment by mimi89999** [comment]
@3m0 Could you add a screenshot?

**Comment by mimi89999** [comment]
@3m0 
![capture du 2015-07-10 17 35 27](https://cloud.githubusercontent.com/assets/8530546/8622142/1f1c4c04-272a-11e5-91f0-93d5bd0ff6df.png)

**Comment by mimi89999** [comment]
And Kaku framed:
![capture du 2015-07-10 17 37 40](https://cloud.githubusercontent.com/assets/8530546/8622197/6b475722-272a-11e5-9654-68aaaa5ddc9f.png)

**Comment by mimi89999** [comment]
@3m0 For me it works fine...

**Comment by EragonJ** [comment]
Updated releases, please go give it a try (No linux here, but if there is nothing wrong, the release should work) thanks.
