### ISSUE TITLE
Previous & Next buttons doesn't work

### ISSUE THREAD

**Issue by Draxler** [EragonJ/Kaku#161]
Test KaKu version / Win7 OS
_______________________

Previous & Next buttons doesn't work in the Kaku player.
- Detailed issue described for each button in the screenshot:

![222](https://cloud.githubusercontent.com/assets/7681671/8556750/576d25e8-24f9-11e5-8708-33772d4a3a74.PNG)

**Comment by EragonJ** [comment]
Well, they will only work when you click on **play all** buttons (by clicking on it, Kaku can get the whole list of tracks), otherwise it will think you keep playing current track. Please give it a try, thanks.

**Comment by Draxler** [comment]
@EragonJ 

OK. Thanks for clarification. I didn't know that. 
I'll do what you propose.

**Comment by EragonJ** [comment]
Mark this as fixed.
