### ISSUE TITLE
Vimeo ''Search'' doesn't work

### ISSUE THREAD

**Issue by Draxler** [EragonJ/Kaku#162]
KaKu Test Version / Win7 OS /

When switch Youtube Search Engine (Source) onto Vimeo in the Settings, Vimeo doesn't work.
Only Youtube works.
Vimeo do not work at all. Whatever Search Term i put into search box nothing happens with Vimeo as a source.

![vimeo02](https://cloud.githubusercontent.com/assets/7681671/8573364/76c5c31c-2591-11e5-8c11-ea3a5ad53d4a.PNG)

![console 1a](https://cloud.githubusercontent.com/assets/7681671/8573375/8148483c-2591-11e5-8976-8945323e1b93.PNG)
![console 1b](https://cloud.githubusercontent.com/assets/7681671/8573391/9172c6a6-2591-11e5-9bd2-2f7e0083ca56.PNG)

**Comment by EragonJ** [comment]
I forgot to put the token for windows build by accident, this will be fixed when you get 1.0.0, thanks.

**Comment by Draxler** [comment]
ok  . :)

**Comment by EragonJ** [comment]
Mark this as fixed first.
