### ISSUE TITLE
Search results, limited only to 30 results or less

### ISSUE THREAD

**Issue by Draxler** [EragonJ/Kaku#180]
Kaku test version / Win OS /

Search results are limited only to 30 results or less. Whatever search term i use, i never get back more then 30 results. Most of the time there are between 24 & 29 results. Sometimes there are 30 results but it's rear.

**Comment by EragonJ** [comment]
Why this is a bug ? There must be `limit` field for every API when exposing to users, otherwise the server will be overloaded if we are going to ask for too many items at the same time.

**Comment by Draxler** [comment]
Wasn't sure if limit is intentional or not, so i reported.  :)  
I kinda hoped it was bug :smile  (like to get more results).

**Comment by EragonJ** [comment]
sure ! thanks for that.
