### ISSUE TITLE
Some Search Results doesn't work where click on it

### ISSUE THREAD

**Issue by Draxler** [EragonJ/Kaku#184]
Latest Win OS / Latest Kaku 1.0.0

Issue described on the Screenshot:

![kaku 23](https://cloud.githubusercontent.com/assets/7681671/8754965/91824f80-2cc7-11e5-95d3-44707f9ecd4d.PNG)

**Comment by mimi89999** [comment]
I don't see the Screenshot

**Comment by Draxler** [comment]
look again :smile:

**Comment by mimi89999** [comment]
Is it #183

**Comment by mimi89999** [comment]
? ;-)

**Comment by Draxler** [comment]
excatley the same  :smile:  

When click on search result in the dropdown meni nothing happens..

**Comment by EragonJ** [comment]
Thank you guys, because this is dup with #183 and we already have some discussions here, let me close #183.

**Comment by EragonJ** [comment]
I am looking into the bug, although the click doesn't work, we can still use keyboard with up / down arrow keys & enter to make it work, I'll fix this in next version.

**Comment by EragonJ** [comment]
After doing `git bisect`, this may be the root cause 81660c8a94809b41568bda3ecc3bf108b1f9d580
