### ISSUE TITLE
add playlist feature not response on Win 8.1

### ISSUE THREAD

**Issue by housemeow** [EragonJ/Kaku#186]
as title, add play list not working in windows 8.1

**Comment by Draxler** [comment]
I also had an issue with ''Add Playlist'' button not working in the first Kaku test version (Win OS).
Try this (worked for me in my case); 
Go into the Settings and click RESET DATABASE button. This  should be it. This worked in my case anyway :)
 
![0b6c43a0-2647-11e5-8282-4d391b85678f](https://cloud.githubusercontent.com/assets/7681671/8766398/11b64060-2e37-11e5-962f-5b965151ed08.PNG)

**Comment by EragonJ** [comment]
interesting, I still can't get it why it would work after clicking on `reset database` ... hmmm !? @housemeow, does this work for you ?

**Comment by housemeow** [comment]
@EragonJ i can't click reset database before change language
when I changed the language, Add playlist button works!

**Comment by EragonJ** [comment]
okay !! Thanks for the hints ! I'll try to fix that in next release, thanks @housemeow !

**Comment by mimi89999** [comment]
@housemeow What language were u using?

**Comment by housemeow** [comment]
@mimi89999 I'm using Traditional Chinese(繁體中文)

**Comment by EragonJ** [comment]
This should be fixed in #194, so let me mark this bug as closed first, thanks all.
