### ISSUE TITLE
Video is not played on Fedora 22

### ISSUE THREAD

**Issue by kevinptt0323** [EragonJ/Kaku#202]
As title, when I click the video to play, it doesn't play the video correctly. And it shows error in console:

    [7777:0723/162835:ERROR:cert_verify_proc_openssl.cc(231)] X509 Verification error unable to get local issuer certificate : 20 : 2 : 4

Run the command below will solve it temporarily:

    ./Kaku --ignore-certificate-errors

The bug is solved in atom/electron#2128, and be merged in electron@0.29.2, so you can upgrade the version of electron!

**Comment by EragonJ** [comment]
#204 was merged, so this should be fixed, thanks @kevinptt0323 & @mimi89999 .
