### ISSUE TITLE
Cannot find 'async' module in Win7 64 bit

### ISSUE THREAD

**Issue by EragonJ** [EragonJ/Kaku#205]
A user reported this to me : 

![11791161_974159369272672_354257947_o](https://cloud.githubusercontent.com/assets/68322/8876959/62d3b334-3255-11e5-89bc-5164ca8f5ec4.jpg)

**Comment by mimi89999** [comment]
@EragonJ Could he try: 
bower install async
and launch kaku again?

**Comment by EragonJ** [comment]
I don't think that's the root cause. There must be something related to environment settings or permissions.

**Comment by EragonJ** [comment]
And after asking for more details, it seems that all needed modules are installed.

**Comment by EragonJ** [comment]
There is another person using win 10 and faced this problem.

**Comment by EragonJ** [comment]
Not sure this is still valid or not, so close first.
