### ISSUE TITLE
Click on search values not working

### ISSUE THREAD

**Issue by uirsevla** [EragonJ/Kaku#209]
When i do a search and then try to click on one of the results it doesnt open the said result and even removes my search. Don't know if it is supposed to be like this or not.

Example: http://gyazo.com/2ef4ba57df191897bd49c7f62e3d4b2a
Example2: http://gyazo.com/9f9a0d3876cbb4e004f64bb33acafed9

PS: It's my first day using Github so i still dont know if it's possible to embed a gif.

**Comment by EragonJ** [comment]
Thanks for reporting, this bug has been fixed in next release, for temporary solution now, you can use arrow keys + enter to search. Thanks.
