### ISSUE TITLE
Add option to backup data to file

### ISSUE THREAD

**Issue by mimi89999** [EragonJ/Kaku#210]

**Comment by EragonJ** [comment]
feel free to add this feature.

**Comment by EragonJ** [comment]
When waiting for dropbox's response, I think this feature does make sense if we got rejected. Let me think how to add this feature into Kaku.

**Comment by EragonJ** [comment]
@mimi89999 If you are working on this part, please let me know.

**Comment by mimi89999** [comment]
No, I'm not working on this part.

**Comment by EragonJ** [comment]
Never mind, I guessed so too, so I just write the patch.

**Comment by mimi89999** [comment]
I wanted to start working on it on tomorow...

**Comment by EragonJ** [comment]
No worries, feel free to try any other if you want :) Thanks.

**Comment by EragonJ** [comment]
If you find anything you want to try, please add an assignee on you so that I can work on the other bugs !
