### ISSUE TITLE
Integrate src/frontend and src/backend

### ISSUE THREAD

**Issue by rickychien** [EragonJ/Kaku#218]
As title. In my opinion, logic between frontend and backend are somehow similar each other. I propose to integrate it first so that it could make our architecture more clear and easier to maintenance.

**Comment by EragonJ** [comment]
Yes, I have to admit that this is a bad design when i start writing the first line for Kaku. Right now I have some thoughts about the new structure :  

```bash
src/public
src/public/css
src/public/less
src/public/images
src/public/fonts

src/views/
src/views/components/ <- from frontend/js/components/
src/views/modules/ <- from frontend/js/modules/
src/views/main.js <- from frontend/js/main.js

src/main.js <- from backend/main.js
src/locales/ <- from backend/locales/
src/models/ <- from backend/models/
src/modules/ <- from backend/modules/
```

What do you think ? @rickychien

**Comment by EragonJ** [comment]
And also, let's move this architecture change to 1.5.0 because this would be a huge change. After this, we can start to investigate how to integrate webpack and maybe get rid of requirejs if needed.

**Comment by rickychien** [comment]
Yeah, it makes sense for me and we should remove backend/main.js since exist two main.js doesn't make sense a little bit. Thus, first thing getting started is to figure out how to integrate backend/main.js with gulpfile.js, keeping build jobs live in one file instead of scattering them in source tree.

**Comment by rickychien** [comment]
I'll start to figure out how to integrate backend/main.js with gulpfile.js if I feel free.

**Comment by EragonJ** [comment]
i am investigating webpack now, will refactor this part at the same time. Please wait for my patch :)

**Comment by rickychien** [comment]
nice!

**Comment by rickychien** [comment]
#230 Here is the first step for getting rid of backend/main.js

**Comment by EragonJ** [comment]
@rickychien +++

**Comment by EragonJ** [comment]
This was fixed in my webpack patch.
