### ISSUE TITLE
Wait for Dropbox team's response

### ISSUE THREAD

**Issue by EragonJ** [EragonJ/Kaku#224]
Right now the team is reviewing the pre-release build about how we integrate dropbox service with Kaku, so this should be fixed first before releasing 1.1.0.

**Comment by EragonJ** [comment]
@rickychien, awesome! Just fixed all needed 1.1.0 bugs, this should be the last one :)

**Comment by EragonJ** [comment]
Got rejected by dropbox, they said our download feature would break their terms. hmmmm, maybe we need to hide download feature.

**Comment by mimi89999** [comment]
I think we should keep download feature and find something else than dropbox

**Comment by EragonJ** [comment]
I think the better way is to remove the button and make the feature work indirectly.

**Comment by Draxler** [comment]
Me also agree with @mimi89999 .  There are other providers which also provide same or even better service then DropBox. There's no need to compromise already implemented function.

**Comment by EragonJ** [comment]
@Draxler well, because after communicating with the team, I agree that we are in the gray area now to be honest. So I think we can still keep that feature, but not so direct. I didn't say I'll remove the feature if you check twice about my words above :)

**Comment by EragonJ** [comment]
#232

**Comment by EragonJ** [comment]
Finally got approved from Dropbox ! Marked this bug as fixed. I'll try to clean up stuffs first and it's time to release 1.1.0.
