### ISSUE TITLE
Video is downloaded into Main Kaku Folder 

### ISSUE THREAD

**Issue by Draxler** [EragonJ/Kaku#236]
Win OS

When video is downloaded from Kaku, video file is stored into main Kaku folder where all Kaku folders and files are stored.

Feature Proposal:
Is there a chance for Kaku to implemented option in the Settings so user could set custom download directory and Folder where downloaded files will be stored?

**Comment by EragonJ** [comment]
Can you upload a gif or screencast for it ? Normally there should be a dialog showing up and ask you where to download you file. If not, it should be the bug in electron, what we did here is use electron's API to trigger File actions.

**Comment by Draxler** [comment]
@EragonJ 

I'm sorry !! 
i'm an idiot..
I was to quick and didn't pay attention .. 
You are correct . It's up to user where file gets stored. User is asked every time before file get's downloaded where to store the file.

**Comment by Draxler** [comment]
@EragonJ 

I'm sorry !! 
i'm an idiot..
I was to quick and didn't pay attention .. 
You are correct . It's up to user where file is stored. User is asked every time before file is downloaded where to store the file.

**Comment by EragonJ** [comment]
no worries, thanks !
