### ISSUE TITLE
(Defferent) Video with the same name(Title) can't be saved into playlist

### ISSUE THREAD

**Issue by Draxler** [EragonJ/Kaku#237]
When i try to save video which have the same artist name and same video name but defferent video version from video which is already in the playlist, it says something like;
''You already have video with this name.Try another.''
These 2 videos have incomon only artist and video name but the video it self is completley deffernt from each other and also musik is defferent (shorter and longer version).
It would be better if videos wouldn't be limited to video name or title. I think it would be better if user could save whatever video, even if some videos have same video names or if video is identical in every way to video already in the playlist. It should be up to user to ''delete'' video from playlist if find identical video in the playlist and don't want it there. This would solved issues like i'm having.
I think this massege should only ''warn'' users that video with the same tile is already in the playlist and let user to procede if choose to and not completley stop user to save the video

**Comment by EragonJ** [comment]
Feel free to provide patch if you want.
