### ISSUE TITLE
Different videos with same title in search results both get highlighted when one chosen.

### ISSUE THREAD

**Issue by htmlguy** [EragonJ/Kaku#241]
When I choose a video from search results in Kaku, where there are multiple identically named videos as results, all with that name get highlighted.

For example: Search for 'Billy Joel Piano Man'. The two first results are both called 'Billy Joel - Piano Man'. When you click on one, both get highlighted.

**Comment by EragonJ** [comment]
This is a known bug, thanks for reporting.

**Comment by EragonJ** [comment]
Use uploader's name as a quickfix for the time being.
