### ISSUE TITLE
Add online DJ feature

### ISSUE THREAD

**Issue by EragonJ** [EragonJ/Kaku#248]
As title, it would be nice to have an online DJ feature so that the others can listen to tracks you are listening.

**Comment by EragonJ** [comment]
Some thoughts here : 

1. compares some possible solutions, I'll use Firebase as our realtime backend (free for 100 concurrent connections) and if Kaku really grows as expected, we can move to our own server.
2. Create one more page called `Online DJ` on the left menu lists.
3. In that page, there are two buttons called `Be DJ` and `Join room` and users can choose which action they want.
4. If you are a DJ, you will get a dashboard containing some information like `Room Id`, `Room Theme`, `Room Name` ... etc.
5. If you are a guest, you can still see some related information but you can't change any of it.
6. For both types of users, they will get a big chatting board on the right and they can have a private talk within the room.
7. In order to achieve above points, each room will be recognized by a random id and they can share this id to friends or on the internet (we can add a share button here to promote Kaku at the same time)

**Comment by EragonJ** [comment]
Some useful lib for emoji
https://github.com/twitter/twemoji
https://github.com/Ranks/emojify.js

**Comment by EragonJ** [comment]
Tasks : 

- [x] users can choose DJ or Guest to play tracks
- [x] Player should be updated to make sure only DJ can control it.
- [ ] fix action buttons under Player
- [ ] dashboard panel should show some useful information (user counts, played tracks ... etc)
- [ ] prepare the base for future feature -  `played tracks`
- [ ] prepare the base for future feature - `online rooms`
- [ ] ... etc

**Comment by Draxler** [comment]
:+1:
