### ISSUE TITLE
Redesign UI

### ISSUE THREAD

**Issue by EragonJ** [EragonJ/Kaku#250]
As title, if any design is willing to help to redesign Kaku, feel free to drop any message below :) Thanks.

**Comment by Draxler** [comment]
So far no UI/Design suggestion or Designing offers..  :-(

**Comment by Draxler** [comment]
@EragonJ 

is there some UI/Design in the workings? or still waiting for some suggestions from others?

Btw. I would realy like to see some dark theme available for Kaku in the future.

**Comment by EragonJ** [comment]
no, if you have any friend who is good at designing, please feel free to introduce him/her to here, thanks.

**Comment by alxhotel** [comment]
I'm not a designer, but I'm making a dark theme.

If you guys are interested I could make a pull request.

**Comment by EragonJ** [comment]
hey @alxhotel ! sounds like a good idea, but I think we may still need to refactor CSS variables to make sure we can easily extend themes ! No matter how, can you still provide a PR first and let me see how's going for your patch ? Thanks :)

**Comment by EragonJ** [comment]
Cleaning old issues, close first.
