### ISSUE TITLE
Show different top tracks based on users' languages (or location)

### ISSUE THREAD

**Issue by EragonJ** [EragonJ/Kaku#251]
As title, it would be more user-friendly to show related top tracks for users. Take myself for example, I would prefer to see more Chinese songs in top tracks instead of songs from America. So, the better way is to show different top tracks based on users' languages (or location)

**Comment by EragonJ** [comment]
Check this : 

https://rss.itunes.apple.com/us/?urlDesc=%2Ftopsongs

Awesome

**Comment by Draxler** [comment]
@EragonJ 

If this feature would be something like on URL you provided then i think this would be ok.
I mean, if user could choose for them selfs, what music app should produce based on Language/location, then this is realy cool feature. 
My only concerne was (when i first read this) that this feature would be automatic and set it up location based on user location and there be no option to opt this out and change back to international, US or UK location (or some other location).

**Comment by EragonJ** [comment]
It will be a dropdown menu to let users choose their country like what you saw at iTunes website. In addition to this, the category will be focused on top songs. So it would be something like :  `https://itunes.apple.com/tw/rss/topsongs/limit=100/explicit=true/json`

**Comment by Draxler** [comment]
:+1:
