### ISSUE TITLE
Vimeo doesn't produce music pictures (posters)

### ISSUE THREAD

**Issue by Draxler** [EragonJ/Kaku#256]
Latest v. Kaku 1.1.0 / Win OS

When i set Vimeo as main video provider there is no Video pictures (posters) which belong each to certain video. Instead there are Kaku placeholders. Previous Kaku version did produce those video pictures for each video.

![kaku 111](https://cloud.githubusercontent.com/assets/7681671/9331210/68351d3c-45be-11e5-92da-059a7574aa64.PNG)

**Comment by EragonJ** [comment]
At least image placeholder is shown here, not so bad. Add bug label for it.
