### ISSUE TITLE
Latest News - Doesn't work (or i don't know how to use it) = Need help in any case :-) 

### ISSUE THREAD

**Issue by Draxler** [EragonJ/Kaku#257]
> ''Latest news''  category in Kaku menu doesn't produce nothing. Page is always empty no metter what provider YT, Vimeo or SC . 
> I like to know if this category is broken (not working) at the moment or is it me that doesn't know how to use it.
> In any case i like to have more info about Latest News.

**Comment by EragonJ** [comment]
It will parse any news I posted in http://kaku.rocks/news.json. This file is hosted in Github Page so you should be able to retrieve it without doing anything.

**Comment by Draxler** [comment]
Ok. thanks. 
Didn't know excatley what to think of ''latest news'' category.

**Comment by EragonJ** [comment]
But it's weird that you can't see any news from it. Are you able to access the json file ? Or is there any error log showing up when you switched to that tab ? 

In the future, if there is anything urgent or update, I'll post there to make sure everyone can read it.

**Comment by EragonJ** [comment]
@Draxler, I'll mark this as closed, feel free to re-open it if you find something interesting.

**Comment by Draxler** [comment]
@EragonJ 

it's ok.. :smile:  I understood you in your first reply, what for is ''Latest News'' and how it's used. 
I gues i should say something earlier, sorry :blush:
