### ISSUE TITLE
add queue for tracks

### ISSUE THREAD

**Issue by EragonJ** [EragonJ/Kaku#279]
As title, it would be useful if we can have a queue for tracks that users can decide which tracks that want to play or not. And also, this queue should work as expected no matter tracks are coming from searches, playlist ... etc.

**Comment by ajkblue** [comment]
Having an "Up Next" option as part of this would be very useful as well, like iTunes. Then users could pick any song they want no matter where they are in their queue and add it as the very next song to play.

**Comment by EragonJ** [comment]
i think a drag & drop feature would be good to fit any case, but it depends on this feature to be implemented first.

**Comment by EragonJ** [comment]
fixed !

**Comment by monkeydri** [comment]
How to add only one track to the play queue ? For example when I search for a song and click "Add to Play Queue" it adds all the search results to the queue (which most often are the same song from different uploaders).

Also it should be possible to remove songs from the Play Queue (and not all the song at the same time).

Kaku v1.8.5

**Comment by EragonJ** [comment]
@monkeydri  if you just want to add one track into play queue, just click on it and it will be stored into the play queue.

**Comment by monkeydri** [comment]
Thank you @EragonJ however once I click a track it plays straight away, it is not added to the queue (and if there was any tracks in the Play Queue, it's cleared and then the only track left is the one which has been clicked).
