### ISSUE TITLE
Run ui test in Travis

### ISSUE THREAD

**Issue by EragonJ** [EragonJ/Kaku#284]
This is a follow-up bug from https://github.com/EragonJ/Kaku/pull/283. Right now we can run ui test by typing `npm run-script uitest-all` in local to see how it works. For CI, I haven't figured out how to make it work on Travis, so open this bug for it.

**Comment by funilrys** [comment]
Did you start working on this @EragonJ ?

**Comment by EragonJ** [comment]
not necessary for now.
