### ISSUE TITLE
Need Full screen + Resize option

### ISSUE THREAD

**Issue by Draxler** [EragonJ/Kaku#292]
Feature request:
Now we have only Full screen option which resize video into full size of monitor sreen. 
I think we need also resize function which would resize video into full size of the app too.

**Comment by EragonJ** [comment]
hmmm, I really don't want to copy the same design from Atraci. Right now, full screen button should fit to any use case here. And with "Best Audio" option, I don't think you will turn on video too often. I'll keep this open and it's welcome to have more opinions here !

Thanks @Draxler

**Comment by Draxler** [comment]
EragonJ

I'm not talking about Design , i'm talking about very useful function which would made posible for user to manipulate video size as they wish. Me personal, i like to watch video and also do some other things at the same time on PC but at the moment, default video size on Kaku is to small to do that. Now i must leave everything what i'm doing and watch video in fullscreen if i want to see some video. if Kaku would have also a Resize function this way video would only resize into size of the app and this way users could manipulate what size they want for the video. 
(You not taking anything away from Atraci it's just a function - usefull one)
