### ISSUE TITLE
''Always on top'' option

### ISSUE THREAD

**Issue by Draxler** [EragonJ/Kaku#293]
Feature request:
I think ''always on top'' option in the Settings would be nice addition if implemented into Kaku.

**Comment by EragonJ** [comment]
@distriker What is this ? No idea. Any demo screenshot ?

**Comment by Draxler** [comment]
@EragonJ
''Always on top'' means that app is always on top of every other open program at the moment even if you use other program at that time then this app. If you have open browser and app at the same time, app will always be visible , no metter if you use browser at that very time, becuase app be on top of the browser if this option is turned on.. This way you can watch video in Kaku in some corner and do whatever on browser at the same time (Popcorn Time have same option). That's's why i also propose resize option in previous request, so you could set video in wanted size and with combination with ''Always on top'' function you could do just that what i decribed before.

**Comment by EragonJ** [comment]
https://github.com/atom/electron/blob/master/docs/api/browser-window.md#winsetalwaysontopflag

Some info from : https://github.com/atom/electron/issues/2097
> The always-on-top option is a hint to operating system or window manager that this window should be put above all non-topmost windows, and it is allowed to have top-most windows overlapping each other on most systems.

**Comment by Draxler** [comment]
@EragonJ 

see sreenshot:
![always on top](https://cloud.githubusercontent.com/assets/7681671/10023676/7f98603c-6153-11e5-84bd-6ab485af24d9.PNG)

**Comment by EragonJ** [comment]
thanks, merged into master.
