### ISSUE TITLE
Need to put some notes about windows build

### ISSUE THREAD

**Issue by EragonJ** [EragonJ/Kaku#295]
As tilte, after testing the windows build with the other beta users. It seems that if there is any folder created with Chinese inside, Kaku itself will not be working correctly without any reason. And in order to prevent the MAX_LENGTH problem, the better way is to tell them unzip the app under "C:\" or "D:\".

Need to put some hints / Q&A page for this part.

**Comment by EragonJ** [comment]
I just leave some news about this in application, will fill another bug in website repo.

**Comment by Draxler** [comment]
@EragonJ 

First, i need to put Kaku Zip file onto dektop, then i need to rename it into 1 letter ''name'' ;
 (Kaku-win.zip name was to long it gave me errors so i rename it into just K) and only then i could unziped Kaku file.  After unzipinig was done then i could rename it back into Kaku and move Kaku folder into whatever directory i want without any issues.

Another thing: Kaku folder in Kaku ZIP file have to long name. After i rename this folder into just Kaku, i could unziped Kaku ZIP file withoout Errors on Desktop and also in Downloads folder. Try to rename it inner folder into just Kaku and users maybe won't have any issues if unziped in desktop or Downloads Folder. Once Kaku is unziped then user could move Kaku foder into whatever directory and their folders without any issues.

![23d4](https://cloud.githubusercontent.com/assets/7681671/10132490/f34c4d9a-65d6-11e5-87df-6cff45de2ede.PNG)
