### ISSUE TITLE
[Mac] el capitan can't open!

### ISSUE THREAD

**Issue by metavige** [EragonJ/Kaku#313]
I download zip, and unzip it.
But can't open Kaku at el capitan.

**Comment by EragonJ** [comment]
ahhh so weird ! Can you try to follow the build process and help to build it on El Capitan ? I am still using Yosemite. thanks !!

**Comment by metavige** [comment]
I clone source. 
After npm instal, I got a lot of error.....


Last part is->
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/Cellar/node/4.1.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Volumes/RamDisk/Kaku/node_modules/mock-browser/node_modules/node-jsdom/node_modules/contextify
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/4.1.1/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/RamDisk/Kaku/npm-debug.log

**Comment by EragonJ** [comment]
interesting, not sure whether this is caused by node version (i use v0.12.4 here) or the new OS.

**Comment by EragonJ** [comment]
It would take while for me to upgrade from Yosemite to El Captain, so if you are willing to help me check this issue, please go ahead. Thanks !!!

**Comment by bu** [comment]
@metavige I've tried the Kaku 1.5.0 build on the El Capitan, and it works like a charm.

But yeah, there's a lot of stuff need to work around the El Captain since it was added tons of security protections. And we're now stick to Node.js 0.12.* versions for building the application, because most of our dependency is not catch up the changes from 0.12 to 4.0. Especially for those require building native modules. This required more work to be done with @EragonJ 

So back to your problem, is it possible for you to check the "System Preference" > "Security & Privacy" > "General" tab, check settings for "Allow apps downloaded from" part? It should be "Anywhere".

If not this issue, please try to take some screenshot of how it hang up. Thanks.

**Comment by metavige** [comment]
This's my security setting
<img width="343" alt="default" src="https://cloud.githubusercontent.com/assets/21334/10361548/5661d272-6ddb-11e5-91b8-163a2346c474.png">

Later I will download release package and try again.

**Comment by bu** [comment]
@metavige Yeah could you try to select "任何來源" here, and try the latest version? Thanks

**Comment by metavige** [comment]
If I download zip and unzip file to folder, u will see icon like this (below image..)
<img width="253" alt="downloads" src="https://cloud.githubusercontent.com/assets/21334/10427634/c58bf476-711d-11e5-9cf0-ce0edf12c11a.png">
I think it's mean this app is not a valid Mac App.

Then I click and run app, this message show like this.
<img width="419" alt="screenshot_2015_10_12_20_12" src="https://cloud.githubusercontent.com/assets/21334/10427640/c80aa0da-711d-11e5-8213-b69c6a56c574.png">

This time I change my security to "Anywhere". What if I miss?

**Comment by EragonJ** [comment]
@bu, any idea about this latest comment (?!)

**Comment by bu** [comment]
@metavige could you re-download, and try again?

**Comment by metavige** [comment]
I re-dowload a new zip (1.5.0) last night.
Is it any difference?

**Comment by EragonJ** [comment]
no idea, this may take longer time to figure out what's wrong there. If there is any update for this bug, we will be back, sorry about that @metavige .

**Comment by metavige** [comment]
I found why my Mac (El Capitan) can't run Kaku.
If you put app at some folder (like Download folder) outside /Applications or $HOME/Applications. This error will happen.

This is not Kaku bug, that's my problem. Sorry.

**Comment by EragonJ** [comment]
oh nice !! thanks for the information @metavige !! But it's kinda weird that why you have a special folder that you can't run any program on it ? Quite interesting ... 

But no matter how, problems are solved ! Thanks :)

**Comment by metavige** [comment]
Maybe it's permission issue. That folder is in my ramdisk.

**Comment by EragonJ** [comment]
haha okay thanks for the information !
