### ISSUE TITLE
fix node-youtube-dl for windows

### ISSUE THREAD

**Issue by EragonJ** [EragonJ/Kaku#327]
As title, in order to make sure I can make Kaku's windows build, I need to rewrite some old codes of `node-youtube-dl`.

https://github.com/EragonJ/node-youtube-dl/commits/master

**Comment by Mimerme** [comment]
Windows build still does not work. Problem with the constants and API keys?

**Comment by EragonJ** [comment]
@Mimerme sorry, didn't notice your message. If you are going to report bug, please file another one in issue tracker with detailed information including OS version, Kaku version and error messages, thanks.
