### ISSUE TITLE
UnCaught (in promise) Error：Command failed：python

### ISSUE THREAD

**Issue by neighborhood999** [EragonJ/Kaku#344]
![](http://i.imgur.com/rf7zruL.png)
![](http://i.imgur.com/0MwBFRa.png)
有些影片載入正常，有些完全就是停在那轉圈圈。
這是 console 的錯誤訊息，再麻煩了，辛苦 @EragonJ 大大了。

**Comment by EragonJ** [comment]
@neighborhood999 好久沒在 github 打中文了真不習慣 xddd  感謝你，我剛發現 youtube-dl 更新了，因為 youtube 改變了他們的加密方式，這真是個麻煩的問題，1.6.0 版就會更新了。

我已經發了一個 bug 希望可以動態讓使用者自動更新這個套件，只是要想想看怎麼解決 hmmmm

**Comment by neighborhood999** [comment]
@EragonJ 我其實很想打英文，可是我的程度不怎麼好所以就索性打中文了XD～
我沒有很認真看錯誤訊息XD，
可是看到 promise 這個單字猜測應該是某個地方失敗了（最近才學習這塊）。

辛苦你了。:+1:

**Comment by EragonJ** [comment]
@neighborhood999 sure !!! 感謝你 xdd 看你對 redux /  react 也有點涉獵，有興趣的話之後可以來幫忙上一些 patch 呀 ~~

**Comment by neighborhood999** [comment]
@EragonJ 啊其實我以前好討厭程式的，是接觸網頁後才開始有興趣的！
其實我不懂的還好多呀，只是看著大家往哪個潮流走就跟著走了（誤）
希望也可以向 @EragonJ 大大學習呀！

**Comment by EragonJ** [comment]
@neighborhood999 :+1: 一起加油 !!! 有 bug 歡迎 report XDD

**Comment by EragonJ** [comment]
Fixed at 0ef3da728036ac3c0164c340f91c77521e5f87e5

**Comment by neighborhood999** [comment]
@EragonJ :+1: 辛苦了！
