### ISSUE TITLE
List existed online DJ channels

### ISSUE THREAD

**Issue by EragonJ** [EragonJ/Kaku#354]
As title, it would be awesome if we can have a list of existed online DJ channels and users can feel free to join the public ones ! (It means we'll need to support public and private channels)

**Comment by mr337** [comment]
+1 think it would be awesome for discovery

**Comment by EragonJ** [comment]
Yes that would be cool ! But too many works stuck here on my side xddd

**Comment by EragonJ** [comment]
https://firebase.google.com/docs/database/security/user-security

**Comment by EragonJ** [comment]
close old issue and will open a new one if needed.
