### ISSUE TITLE
use online service to handle translation

### ISSUE THREAD

**Issue by EragonJ** [EragonJ/Kaku#356]
right now the translations get more complicated now, so it would be nice that we have a service to handle this part and ask volunteers to translate if there is any change.

**Comment by EragonJ** [comment]
registered an account on getLocalization now !

**Comment by EragonJ** [comment]
sad it seems there is no free account any more. need to find other alternatives

**Comment by EragonJ** [comment]
Noticed that getLocalization may have no community account anymore (sad). If anyone has any idea about this, feel free to comment below  !

**Comment by seppi91** [comment]
Maybe you could use Transifex (https://www.transifex.com/) instead?

**Comment by EragonJ** [comment]
@seppi91 I didn't find free plan for open source project from the website. Any shortcut ?

**Comment by EragonJ** [comment]
ohoho it's on the bottom of plans !! Didn't notice that !!! I just registered an account and will share the news with all contributors here later after I setup all craps :P

**Comment by EragonJ** [comment]
Thanks @seppi91 ++++ Hope you can join the translation as well !! See you soon :)

**Comment by EragonJ** [comment]
I'll close this issue first and ask for help in another issue ! Thanks all !!

Help to translate Kaku at https://www.transifex.com/kaku/kaku/ !

**Comment by seppi91** [comment]
Something is wrong with your provided hyperlink:

Transifex shows an error:
"Looks like you followed a bad link. If you think it's our fault, please let us know."

**Comment by EragonJ** [comment]
@seppi91 sorry, i forgot to change to old one , please try this https://www.transifex.com/kaku/desktop-app/ !

**Comment by EragonJ** [comment]
For anyone who is interested in translation, please check the new issue here - https://github.com/EragonJ/Kaku/issues/377
