### ISSUE TITLE
Support Chromecast

### ISSUE THREAD

**Issue by yurenju** [EragonJ/Kaku#359]
#### Summary
Support Chromecast

#### User Story
As a `user`, I want `to show video content on other device via chromecast` so that I can `watch or listen content from other device`.

#### Behaviour of the UI
* a button to choose which chromecast device you want to deliver content
* when content is delivered to chromecast device, kaku app should just show a image instead of video
* a button to disconnect from chromecast
* when disconnect from chromecast, kaku app should play the video content again

#### Design Reference / Mockup / Sketches (optional)
![chromecast-spotify](https://cloud.githubusercontent.com/assets/22155/11761017/21772342-a0ed-11e5-9f21-76951262f376.gif)

#### References (optional)
* [node-castv2-client - A Chromecast client based on the new (CASTV2) protocol](https://github.com/thibauts/node-castv2-client)
* [chromecast-js - Chromecast Node.js module](https://github.com/guerrerocarlos/chromecast-js)
* [node-mdns-js - Pure JavaScript/NodeJS mDNS discovery implementation.](https://github.com/mdns-js/node-mdns-js)

**Comment by EragonJ** [comment]
@yurenju for the UI part, you can try to add one more button under `player/control-buttons` for testing :)

**Comment by EragonJ** [comment]
Thanks for trying to implement this feature and if you need any help, just let me know :)

**Comment by yurenju** [comment]
:+1:
