### ISSUE TITLE
Port to Windows OS and others

### ISSUE THREAD

**Issue by EragonJ** [EragonJ/Kaku#36]
This is very important that needs to be fixed before July, 2015.

**Comment by mimi89999** [comment]
What about #16 ?

**Comment by EragonJ** [comment]
Are you sure that works ??

http://electron.atom.io/docs/v0.27.0/tutorial/application-distribution/

**Comment by mimi89999** [comment]
#38 should be OK.

**Comment by EragonJ** [comment]
No, that doesn't work. If you double check your code, you still trying to build mac build instead of Windows's. Never mind, I'll find a windows to fix this later, thanks.

**Comment by mimi89999** [comment]
I'm on Linux...

**Comment by EragonJ** [comment]
well, in order to fix this bug, you need a windows to test with ... (sad)

**Comment by mimi89999** [comment]
@EragonJ I changed platform from 'win' to 'win32'. It should work now.

**Comment by EragonJ** [comment]
Well, I did test by myself few days ago and there are still some codes that needs to be updated to make Kaku work in Windows, so this is not as simple as one-line fix. Have you ever tried your patch on Windows ?
