### ISSUE TITLE
Nothing happens when the song ends....

### ISSUE THREAD

**Issue by mimi89999** [EragonJ/Kaku#365]
I have to change to the next track. Kaku won't do it...

**Comment by EragonJ** [comment]
Please provide more information including : 

1. Kaku version
2. OS platform and version
3. ctrl + alt + i (windows) or cmd + option + i (mac) to turn on inspector and switch to `console` panel and copy the error message you found
4. which song caused the problem or you can even use `settings > backup to local` feature to export your playlist contains that song and share it here for debugging use.
5. any error you found on the UI part

with these information, it would be helpful to help me dig out the problems, thanks :)

**Comment by mimi89999** [comment]
Kaku version: 1.6.1
OS: Linux debian 4.3.0-1-amd64 #1 SMP Debian 4.3.3-2 (2015-12-17) x86_64 GNU/Linux
The problem is even in "Top Rankings"
I'm using YouTube with my own API key.
I don't have errors.

**Comment by EragonJ** [comment]
@mimi89999 which country's top ranking and which song

**Comment by mimi89999** [comment]
Poland

**Comment by EragonJ** [comment]
which song ? top 10 tracks work fine here on my laptop

**Comment by mimi89999** [comment]
@EragonJ https://lebihan.pl/kaku-3.ogv

**Comment by EragonJ** [comment]
ahhh why you gave me an ogv file XD?

**Comment by mimi89999** [comment]
I took this screencast to show the issue...

**Comment by EragonJ** [comment]
.... well, you totally report an invalid bug. From the video, you just clicked the track and played one song in no-repeat mode. Of course when the song ended, the player got stopped. It's quite normal for normal player isn't it ? I got so surprised that you didn't know that .... 囧

If you are going to play more tracks at the same time, you need to use the `play all` button on the top-right. 

This bug is invalid to me so close first. Hope my comment did help you in some ways. Thanks.

**Comment by mimi89999** [comment]
I thought the ***play all*** button was a toggle button. In that case I could enable ***play all***, play a song chosen by me and then automatically play the next song...

**Comment by mimi89999** [comment]
Related to #296

**Comment by mimi89999** [comment]
@EragonJ 
> Of course when the song ended, the player got stopped. It's quite normal for normal player isn't it ? I got so surprised that you didn't know that ....

https://lebihan.pl/musicplayer.ogv

**Comment by EragonJ** [comment]
Seems like our beloved music players implement the rules in different ways, so I don't have any comment for this part. If anyone has different idea for this part, feel free to leave your comment here.
