### ISSUE TITLE
No streaming option

### ISSUE THREAD

**Issue by zatherz** [EragonJ/Kaku#376]
Currently Kaku downloads the full song to your hard drive which can take a long time, it'd be useful to have an option to stream from the site just like Atraci.

**Comment by EragonJ** [comment]
Ahhh ... if you did check the settings page, you'll notice that there is one option to let you change the streaming from video to audio. And if you are using audio format, it would be blast-fast to download the whole song.

**Comment by EragonJ** [comment]
I think that should answer your question so i'll close first. Feel free to reopen if you found any other bugs.

**Comment by zatherz** [comment]
Actually, I have had this on before posting the issue. I feel like a streaming option would be very useful for when the connection is wonky.

**Comment by reddit-is-fun** [comment]
@EragonJ 

I would be clearer if the video player space would disappear when only the audio stream isselected

![2016-02-19 16_55_01-kaku](https://cloud.githubusercontent.com/assets/14923168/13178810/942863ca-d729-11e5-9ad2-72f362e9508d.png)

![2016-02-19 16_55_01-kaku](https://cloud.githubusercontent.com/assets/14923168/13178838/b731d252-d729-11e5-86b1-3ce51a55bc59.png)

**Comment by EragonJ** [comment]
i think the change would be minor and i don't plan to implement that because it's kinda weird to keep changing UI there. Thanks for providing feedbacks here.

**Comment by zatherz** [comment]
I do not like the way you're going with this project, "it's kinda wierd" and "the change would be minor". The video view is absolutely useless with the option selected and it actually looks "kinda wierd" having it without having any video. The suggestion screenshot by @reddit-is-fun looks much cleaner.

**Comment by reddit-is-fun** [comment]
@zatherz You're free to submit a pull request and the dev might accept it. In my opinion this would be an improvement, but definitely a minor one. Developers have been cooperative so far.

**Comment by EragonJ** [comment]
come on ... it's open source project and it's always welcome to have you guys' PR if you think things are important. It's my personal idea about that improvement and I still got more important things to do like syncing, online DJ, mobile app version and so on.

It would be thankful if you can jump in and be part of contributors @zatherz ! It would be awesome.

@reddit-is-fun thanks for leaving your idea here. :)
