### ISSUE TITLE
Update react

### ISSUE THREAD

**Issue by neighborhood999** [EragonJ/Kaku#379]
Now Kaku dependencies: react version is `0.13.3` and we will update to `0.14.x` version.

**Comment by neighborhood999** [comment]
Maybe we can wait until next version...15.0.0
@EragonJ See [new-versioning-scheme](https://facebook.github.io/react/blog/2016/02/19/new-versioning-scheme.html)

**Comment by EragonJ** [comment]
cool, interesting notes. Let's keep watching the change of React :)

**Comment by neighborhood999** [comment]
@EragonJ I have already try to

**Comment by neighborhood999** [comment]
Next time I will try to update to 15.0.x version.

**Comment by EragonJ** [comment]
Sure no problem !
