### ISSUE TITLE
Integration of pleer, music.163.com / netease

### ISSUE THREAD

**Issue by seppi91** [EragonJ/Kaku#382]
Until now kaku supports: Youtube, Vimeo and Soundcloud. All these services are already integrated in the more succesful TomaHawk Player (https://www.tomahawk-player.org/).
To differentiate more from Tomahawk I would recommend to integrate some services which are not that common as youtube/vimeo and so on.

There are already some quite nice wrappers written on github, which could be found quite easily. Here are just some results of my search:
https://github.com/fraserxu/music163-cli
https://github.com/micaelsouza/pleer

**Comment by neighborhood999** [comment]
@seppi91 WOW！it's awesome

**Comment by EragonJ** [comment]
thanks @seppi91, I now the concern you have here. In stead of adding more platform, I prefer to make t he player more powerful with some awesome features that we already use in daily life a lot like : streaming, online DJ ... etc.

So for the time being, the main focus for Kaku will still be these features and maybe the platform can be supported later (no plan yet). No matter how, any feedback is appreciated. thanks !

**Comment by EragonJ** [comment]
I think we need to focus on main streaming platform first and make sure the application is stable enough. We'll go over these things later when we have time ;)
