### ISSUE TITLE
Remember playback position

### ISSUE THREAD

**Issue by 07416** [EragonJ/Kaku#384]
I also use Kaku for listening podcasts (on YouTube), it would be great if the program would remember the playback position for the most recent tracks, at least for the stream currently open.

**Comment by EragonJ** [comment]
If you can give me more example about how the other programs work in this way, it would be helpful to know more details about this feature !

**Comment by EragonJ** [comment]
BTW, any patch is welcome :)

**Comment by reddit-is-fun** [comment]
I'm not aware of any other programs that do this, even YouTube fails to save the video position (when cookies are enabled) and I'm not sure if the feature even works anymore. Probably needs some sort of custom implementation.
I've also noticed that YT playback can be interrupted (stream has to be restarted) when the video is on pause for a long time, but that happens on the website also.

**Comment by EragonJ** [comment]
Ok, if you got any more details for this, feel free to comment down below. I'll mark this as feature first but this may not be in a high priority.
