### ISSUE TITLE
Scrobble what the user is listening (Last/Libre FM)

### ISSUE THREAD

**Issue by ivanhercaz** [EragonJ/Kaku#392]
Hi everyone,
I'm very happy with the Kaku's progress, you're working fine guys! When I have a bit of time I will try to update Spanish translation. But now, I'm going to "give" an idea: **make an option to scrobble what the user is listening in its Last (or Libre) FM profile**.

I don't know if it's the correct place to post that possible feature or if you already had that idea, but I think that it could improve the social side of Kaku.

Regards, Iván

**Comment by EragonJ** [comment]
Because not all users all use LastFM here, I was thinking whether the better way here is to have Kaku's own Scrobble list hmmmmm it's worth to discuss

**Comment by distriker** [comment]
Could be a good idea give to the users the opportunity to select what scrobblers they want to use. For example, choose between Last FM, Libre FM or Kaku native scrobbler.

**Comment by EragonJ** [comment]
@distriker , can you help to list down some hot scrobblers here (with link to documentations) ? It would be helpful for all to discuss !

**Comment by distriker** [comment]
Of course @EragonJ! I know three scrobblers Libre FM, Last FM y Musicovery.
- **Libre FM**. [API] (https://git.gnu.io/foocorp/librefm/wikis/Librefm_API) and [cheatsheet] (https://git.gnu.io/foocorp/librefm/wikis/Librefm_API_methods).
- **Last FM**. Everything in its [API documentation] (http://www.last.fm/api/intro).
- **Musicovery**. [API documentation] (http://musicovery.com/api/V3/doc/documentation.php).
Ay the beginning there is the three scrobblers that I know but I will search more to try to collect API scrobblers and value it in this discuss.

Keep in touch!

**Comment by EragonJ** [comment]
I'll close this outdated issue first and feel free to reopen this issue if needed :)
