### ISSUE TITLE
build error for the first time ?

### ISSUE THREAD

**Issue by EragonJ** [EragonJ/Kaku#396]
#### Bug

```bash
> youtube-dl@1.11.0 postinstall /Users/EragonJ/.../Kaku/desktop/node_modules/youtube-dl
> node ./scripts/download.js

module.js:340
    throw err;
    ^

Error: Cannot find module 'generate-object-property'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/EragonJ/.../Kaku/desktop/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/index.js:1:76)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

#### Steps to reproduce the bug

Looks like when doing `npm install` for the first time, this error will show up

**Comment by EragonJ** [comment]
may be related to https://github.com/EragonJ/Kaku/issues/390, but with different error message

**Comment by EragonJ** [comment]
Looks like something is wrong when downloading youtube-dl on Windows which will cause black screen, need to figure out what's wrong there.

**Comment by olgierd-on-fire** [comment]
That causes when I translate to korean.

**Comment by olgierd-on-fire** [comment]
When you run Kaku, then you can't search and don't see content section. It's just white screen. But you configure language one more time in Settings, everything is gonna fine.

**Comment by olgierd-on-fire** [comment]
My tests are all clear. Is there anything I can help?

```shell
 ./node_modules/mocha/bin/mocha -u tdd -t 5000 --reporter dot --compilers js:babel-core/register --require ./tests/unit/setup.js --harmony_arrow_functions 'tests/unit/*.test.js'



  ․․․․․․․․․․․Removed track -  [ { artist: '周杰倫', title: '我要夏天' } ]
․․․․․․[SECURITY] node-uuid: crypto not usable, falling back to insecure Math.random()
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․we can't find any playlist with id -  id0
․․․․․․․․․․․

  57 passing (797ms)
```

**Comment by EragonJ** [comment]
@mimi89999 @neighborhood999 do you guys have linux ? Someone dropped me a message about that they can't use 1.7.0 on Linux XDDD

**Comment by mimi89999** [comment]
Yes, I use GNU/Linux. I will try 1.7.0 when I will be back home.

**Comment by neighborhood999** [comment]
@EragonJ I can use 1.7.0 in Linux (ubuntu).

**Comment by MarcinWieczorek** [comment]
> @mimi89999 @neighborhood999 do you guys have linux ? Someone dropped me a message about > that they can't use 1.7.0 on Linux XDDD 
Funny as hell... Yeah, we can't.

Tomorrow I will compile it in debug mode and let you know if anything new happens. Btw. I'm getting a black (often glitchy) screen and nothing more on:
> Linux 4.5.4-1-ARCH SMP PREEMPT Wed May 11 22:21:28 CEST 2016 x86_64 GNU/Linux

**Comment by mimi89999** [comment]
@EragonJ 
I built Kaku and...:
>michel@debian:~/git/Kaku$ electron .
App threw an error when running Error: companyName is a required option to crashReporter.start
    at CrashReporter.start (/usr/local/lib/node_modules/electron-prebuilt/dist/resources/electron.asar/common/api/crash-reporter.js:47:13)
    at Object.<anonymous> (/home/michel/git/Kaku/bootup.js:7:24)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at loadApplicationPackage (/usr/local/lib/node_modules/electron-prebuilt/dist/resources/default_app.asar/main.js:252:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-prebuilt/dist/resources/default_app.asar/main.js:292:5)
    at Module._compile (module.js:541:32)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: companyName is a required option to crashReporter.start
    at CrashReporter.start (/usr/local/lib/node_modules/electron-prebuilt/dist/resources/electron.asar/common/api/crash-reporter.js:47:13)
    at Object.<anonymous> (/home/michel/git/Kaku/bootup.js:7:24)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at loadApplicationPackage (/usr/local/lib/node_modules/electron-prebuilt/dist/resources/default_app.asar/main.js:252:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-prebuilt/dist/resources/default_app.asar/main.js:292:5)
    at Module._compile (module.js:541:32)

**Comment by MarcinWieczorek** [comment]
1.7.0 compiles just fine, I tested it. I doesn't work tho.

**Comment by mimi89999** [comment]
@MarcinWieczorek Open bootup.js, go to line 43, change for `'frame': true` and run gulp and electron again.

**Comment by MarcinWieczorek** [comment]
Yeah I will when I find some time

**Comment by EragonJ** [comment]
hmmm it's quite weird that Kaku 1.7.0 doesn't work for you @MarcinWieczorek.

Can you guys (+ @mimi89999 @neighborhood999 ) share the OS information here and see whether it only failed on certain platform ?

**Comment by EragonJ** [comment]
@mimi89999 you reminded me that it would be great to have an article about this debugging tips. thanks.

**Comment by EragonJ** [comment]
Just built Kaku on a clean environment and everything works well, so close this first and see what's going on later.

# env
1. Mac OS X 10.11.5
2. node 5.1.1
3. npm@2

**Comment by MarcinWieczorek** [comment]
![](http://i.marcin.co/2016-06-16_65508e.png)
This is how kaku with frame=true looks.

**Comment by mimi89999** [comment]
And with `frame=false`?

**Comment by MarcinWieczorek** [comment]
Black and glitching but without the frame and menu lol

**Comment by mimi89999** [comment]
What is in the console?

**Comment by EragonJ** [comment]
@MarcinWieczorek it would be nice that you can help to figure out the problem because I don't have the same (especially Linux) environment here. I think you already successfully built Kaku by yourself (which is awesome), so I think it would be easier to figure out what's going on here.

Checked from your screenshot, I think this may be the problem of Electron (not sure), so if possible, it would be nice that you can try to run Kaku with different electron (especially Electron 1.0.0 already got released few weeks ago).

And like what @mimi89999 said here, you can also check whether there is any error message showing up from the console (command + alt + i) 

https://github.com/EragonJ/Kaku#setup-environment

**Comment by MarcinWieczorek** [comment]
Should I expect DevTools to work?
http://i.marcin.co/2016-06-16_c5b1be.png

**Comment by EragonJ** [comment]
@MarcinWieczorek what the hell is that black screen XDDD 

Basically the devTool should work well (especially they all work well right now on Mac & Windows so that's why I guessed that this may be Electron's issue but I am not sure)

It would be awesome that you can try to build Kaku based on new version of Electron and share anything you found here. That would be super useful !! 

@neighborhood999 I remembered last time when we were testing Linux version on Ubuntu, that worked well as expected, right ?! Any idea about this black screen issue xD?

**Comment by mimi89999** [comment]
@MarcinWieczorek `electron -v`

**Comment by MarcinWieczorek** [comment]
So I seem to be using runtime v1.2.3, but I built Kaku with 0.36.0
```plain
$ electron -v
v1.2.3
```

**Comment by EragonJ** [comment]
@MarcinWieczorek so in which version, did you see the black screen ? Both of them ? And BTW, did you try our latest release (Linux 64 & Linux 32) and Does it work well on your machine ?

**Comment by MarcinWieczorek** [comment]
I managed to run the app with `gulp watch`

```plain
 06/17/16 13:57  ~/packages/kaku/src/Kaku-1.7.0   master  gulp watch                 
[13:57:13] Using gulpfile ~/packages/kaku/src/Kaku-1.7.0/gulpfile.js
[13:57:13] Starting 'watch'...
[13:57:13] Finished 'watch' after 25 ms
[2016-06-17T11:57:13.622Z] [electron-connect] [server] started electron process: 27917
[2016-06-17T11:57:13.623Z] [electron-connect] [server] created and listening on 30080
(electron) companyName is now a required option to crashReporter.start
Hash: b4d8816664ee1903d5fa
Version: webpack 1.13.1
Time: 3799ms
          Asset    Size  Chunks             Chunk Names
kaku.bundled.js  641 kB       0  [emitted]  main
    + 125 hidden modules
```

PS: add Polish to translations on tx

**Comment by EragonJ** [comment]
@MarcinWieczorek ok thanks for the info.

I am not sure why the black screen is there, but if you tried to open Kaku when bootup, we'll put an overlay on it before things are loaded.

You can check related codes here : https://github.com/EragonJ/Kaku/blob/master/src/public/less/components/global.less#L36

Not sure whether this is transparent color issue when using `rgba` here in Linux. If possible, can you try to comment out the background color here, or try only to load a simple `<div>` DOM here at https://github.com/EragonJ/Kaku/blob/master/src/main.js#L203 ? 

I think maybe we can try to bisect the problem here and see which component messed up the UI.
