### ISSUE TITLE
Ignore some unused files under src/frontend/vendor

### ISSUE THREAD

**Issue by EragonJ** [EragonJ/Kaku#40]
As title, the better way is to find a better source that the endpoint only includes needed files instead of unrelated files. It's also a good time to think whether we should move to `npm` to control all 3rd party libraries because if they are on bower, they are also on npm ! By doing so, we can use `package.json` as a centralized place to control all these dependencies.

**Comment by rickychien** [comment]
Yeah, and later we could migrate requirejs to webpack to manage module system \o/

**Comment by EragonJ** [comment]
@rickychien need your help, man !

**Comment by rickychien** [comment]
PR is coming but I ran into a issue in classnames, I need to fix it first

**Comment by EragonJ** [comment]
great !! I think we can use a special branch for this, do you want to be a main contributor for this repo XD? I can give you permission ! @rickychien

**Comment by rickychien** [comment]
Nice shot! I'm glad to hear that!!

We can have a beer someday and discuss the future about how to integrate kaku with webpack.

**Comment by EragonJ** [comment]
@rickychien added !

**Comment by EragonJ** [comment]
@rickychien , join https://gitter.im/EragonJ/Kaku to discuss if you want ! I already setup notification on it and every message will be forwarded to my mailbox.

**Comment by rickychien** [comment]
#216
