### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by neighborhood999** [EragonJ/Kaku#405]
fix typo: **播放下一首歌曲**

![Imgur](http://i.imgur.com/LVvsskk.png)

I will have new PR and fix it.

**Comment by EragonJ** [comment]
@neighborhood999 please help to update that value on the translation service and tell me when you are done :)  Thanks

**Comment by neighborhood999** [comment]
Yep, I already update translation service, and I edit `src/locales/zh-TW` file.
But it's weird！Kaku still display `播放前一首歌曲`.
