### ISSUE TITLE
refactor existing codes to use ES6+ syntaxes

### ISSUE THREAD

**Issue by EragonJ** [EragonJ/Kaku#408]
As title, almost new components and modules are all written in ES6+ syntaxes already. In order to make the codebase cleaner and easy to understand, need to refactor every piece to ES6.

**Note:** there are some components are written in ES5 by design when using React mixins, but not sure now whether it's safe to write them in ES6+ or not, need to double check.

**Comment by EragonJ** [comment]
This is a longterm issue and can be solved one by one.

**Comment by neighborhood999** [comment]
@EragonJ I have time I will help this. Next month I will be a solder qq.

**Comment by neighborhood999** [comment]
Maybe we can open **Roadmap** issue, help check where already update to ES6 syntax.

**Comment by EragonJ** [comment]
ok cool, thanks @neighborhood999 ! let me close this one.
