### ISSUE TITLE
Dropbox is deprecating v1 API

### ISSUE THREAD

**Issue by EragonJ** [EragonJ/Kaku#416]
#### Bug

Just got the email from Dropbox which tells me that they are going to deprecate v1 API by Sep 28th, 2016. In this way, we need to update the DropboxBackuper to use the latest API.

References:
1. https://www.dropbox.com/developers/reference/migration-guide
2. https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/

**Comment by neighborhood999** [comment]
local backup seems like failed...
