### ISSUE TITLE
[archlinux] Bug : Not working

### ISSUE THREAD

**Issue by funilrys** [EragonJ/Kaku#421]
#### Bug

![deepinscreenshot20160829100748](https://cloud.githubusercontent.com/assets/14127285/18044983/b81a7a32-6dd0-11e6-8dab-a9fdaf9fea8d.png)
#### Steps to reproduce the bug

Just start your app in arch ! :D 
#### What is your Kaku version ?

1.7.0
#### What is your OS with version number ?

Linux XXXXXXXX 4.7.2-1-ARCH #1 SMP PREEMPT Sat Aug 20 23:02:56 CEST 2016 x86_64 GNU/Linux
#### Which platform you are using to listen to music ?

---
#### Which track format you are using ?

**
#### Is there any error coming from Inspector ?

What do you mean when you say inspector ?
#### Others

Okay let's go ! I'm trying to update the package in AUR but we just can't see anything ... Do you have a log file somewere so I can check ? Or can you recomment dependency that I've missed ? 

This appear if I upadate localy PKGBUILD to 1.7.0 
And after downloading your releases ...

Hava nice day and thanks in advance  for answers !

**Comment by EragonJ** [comment]
@funilrys sorry I don't have linux to test that part and arch build is mainly maintained by the community, if you have any idea for this issue, feel free to share here or help to fix that :) Thanks !

**Comment by funilrys** [comment]
Okay can you tell me what's the role of inspector so i can find an equivalent ? You don't log the app ?

**Comment by EragonJ** [comment]
@funilrys please check this part - http://kaku.rocks/docs/en/how-to-report-the-bug.html. But I am not sure whether you can still turn that on there because right now it looks like the whole app is not working at all.

**Comment by Pival81** [comment]
there is really no other way to debug it?

**Comment by EragonJ** [comment]
@funilrys @Pival81 I think another way is to use `npm run start` in the root of Kaku and see what will happen. You can check `package.json`, it's just a command to run preinstalled `electron` binary to start Kaku from its source code (don't forget to read prerequisites in wiki to make sure you did prepare everything first!)

Hope this helps, feel free to comment down for more ideas and we can discuss here.

**Comment by Pival81** [comment]
here is the log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/sbin/npm', 'run', 'start' ]
2 info using npm@3.10.6
3 info using node@v6.5.0
4 verbose stack Error: ENOENT: no such file or directory, open '/home/pival81/Scaricati/Kaku-linux64/package.json'
4 verbose stack     at Error (native)
5 verbose cwd /home/pival81/Scaricati/Kaku-linux64
6 error Linux 4.7.2-1-zen
7 error argv "/usr/bin/node" "/usr/sbin/npm" "run" "start"
8 error node v6.5.0
9 error npm  v3.10.6
10 error path /home/pival81/Scaricati/Kaku-linux64/package.json
11 error code ENOENT
12 error errno -2
13 error syscall open
14 error enoent ENOENT: no such file or directory, open '/home/pival81/Scaricati/Kaku-linux64/package.json'
15 error enoent ENOENT: no such file or directory, open '/home/pival81/Scaricati/Kaku-linux64/package.json'
15 error enoent This is most likely not a problem with npm itself
15 error enoent and is related to npm not being able to find a file.
16 verbose exit [ -2, true ]
```

**Comment by EragonJ** [comment]
@Pival81 not sure why there is no `package.json`, did you clone this project from GitHub ? 

And also, in order to decrease any factors, please follow https://github.com/EragonJ/Kaku/wiki/Setup-environment to use nvm and setup the same node / npm version (at least should be close)

And don't forget to prepare built assets first - https://github.com/EragonJ/Kaku/wiki/How-to-develop

**Comment by funilrys** [comment]
Okay let's debug :D @EragonJ

**Comment by EragonJ** [comment]
thanks @funilrys !! any help would be appreciated !

**Comment by funilrys** [comment]
I don't really know were is the problem but you can find the strace [here](https://gist.githubusercontent.com/funilrys/b158c6da5354a045387353afea710e75/raw/af8411ae6e30e568ee9077ef043807ee81bd2948/strace-Kaku)

**Comment by funilrys** [comment]
We can maybe solve this ... 
What are the difference between 1.6.1 and the last release ? 
Cause actually the 1.6.1 work perfectly on arch !!

**Comment by EragonJ** [comment]
@funilrys @Pival81 mind give 1.8.0 a try :P ? I think it's a good time to use AppImage format for linux users now :) I already tested the latest version on Ubuntu, so hope this does fix the problems that you guys encountered before.

If things are going well, i'll close this issue ! And by the way @funilrys , I have noticed that you did maintain tons of projects on AUR here https://aur.archlinux.org/packages/?SeB=m&K=funilrys ! Are you willing to help on maintaining future release of Kaku for us :P ? 

Thanks ahead BTW !

**Comment by funilrys** [comment]
Hello @EragonJ,
First sorry for the late answer I was on holiday. 
I tested it yet and all right now :) 

I'll be glad to maintain Kaku but now it's a bit late someone adopted it. But if it's someone of your team, I'll be glad to be co-maintainer.

Have a nice day !

**Comment by EragonJ** [comment]
Thanks @funilrys !! I don't know who the maintainer is, but i remembered long time ago the maintainer said he already stopped maintaining that AUR repo anymore, that's why I asked whether you can take it over or not.

But I am not sure why it's alive now, if possible, maybe you can try to ask to be a co-maintainer for it ?

And it looks like the AppImage format works well for archlinux ! I'll close this issue first and feel free to reopen if you find anything wrong.

**Comment by funilrys** [comment]
Hello @EragonJ , 
Just for information, I'm now the maintainer of kaku on archlinux.

**Comment by funilrys** [comment]
@EragonJ Do you think it's a good idea to add a Arch Section like I did with Laverna [here](https://github.com/Laverna/laverna/pull/645/files) ?

Here's the text : 

#### Arch Linux (or derived distributions)

The package can be found [here](https://aur.archlinux.org/packages/kaku-bin/). 

For installation please use :

```bash
$ yaourt -S kaku-bin
```

For issue about installation please report [here](https://github.com/funilrys/PKGBUILD/issues/new) or contact [@funilrys](https://github.com/funilrys) on gitter [here](https://gitter.im/funilrys_/PKGBUILD)

**Comment by EragonJ** [comment]
@funilrys added :)

**Comment by funilrys** [comment]
Wow just realized that this issue was because Kaku use and work perfectly with node@v5.1.1 ... and the version installed at the time of the issue was node@v6.5.0 ...
@EragonJ

**Comment by funilrys** [comment]
Wow just realized that the main problem was because our version of node at this time was > 5.1.1 @EragonJ

**Comment by EragonJ** [comment]
@funilrys ??? so what's the version that you are using ?

**Comment by funilrys** [comment]
@EragonJ at the time of that issue, it was node@v6.5.0
