### ISSUE TITLE
官网下载的mac客户端无法解压

### ISSUE THREAD

**Issue by ElfSundae** [EragonJ/Kaku#423]
![qq20160830-0](https://cloud.githubusercontent.com/assets/526008/18091622/def95f3e-6efb-11e6-9a7a-9e54db7ffc78.png)

**Comment by EragonJ** [comment]
@ElfSundae I tried that on my laptop and it works fine. It's just a simple zip file and should be able to unzip, can you try on different laptop for it ? I am suspecting this might be issue on your laptop ?

**Comment by ElfSundae** [comment]
@EragonJ Thanks, I redownload and it can be unzipped now.

**Comment by EragonJ** [comment]
ok cool, thanks !
