### ISSUE TITLE
Invisible dropdown menu items

### ISSUE THREAD

**Issue by mantasjk** [EragonJ/Kaku#425]
#### Bug
Under Settings tab, when opening Default Language or other dropdown menu whole menu appears black.
#### What is your Kaku version ?
1.7
#### What is your OS with version number ?
I am under Ubuntu 16.04 with Gnome 3.20.
#### Is there any error coming from Inspector ?
No errors in Inspector, but when Kaku is run from terminal I get this: 
"[21575:0904/164806:ERROR:gles2_cmd_decoder_autogen.h(2893)] [.Compositor-0x35a3b6e5b00]GL ERROR :GL_INVALID_ENUM : glTexParameteri: target was GL_FALSE"

**Comment by EragonJ** [comment]
cool thanks @mantasjk , there is another issue got reported with details screenshot, i'll mark this one as dup of #428, for more discussions, plz check that thread!
