### ISSUE TITLE
Unable to save playlist locally

### ISSUE THREAD

**Issue by dln949** [EragonJ/Kaku#426]
#### Bug

When I attempt to save a playlist locally, nothing happens.  I do NOT see a window that allows me to explore and choose local directories.  

#### Steps to reproduce the bug

First, Open Kaku and you can see your playlist.  

Next, click setting and you can see backup

Backup to Local.  

At this point, nothing happens.  

#### What is your Kaku version ?

1.7.0 (for example)

#### What is your OS with version number ?

Ubuntu 16.04; unity

#### Which platform you are using to listen to music ?

YouTube 

#### Which track format you are using ?

best video (or best audio)

**Comment by neighborhood999** [comment]
Hey @dln949 thanks your report, on PR #419 already fixed, next time release will fix this problem.

**Comment by EragonJ** [comment]
As @neighborhood999 said, this should be solved in later release no matter how. close first, thanks !
