### ISSUE TITLE
List keyboard shortcut

### ISSUE THREAD

**Issue by winardiaris** [EragonJ/Kaku#427]
#### Others

Where I can see keyboard shortcuts?

**Comment by EragonJ** [comment]
@winardiaris right now only these few shortcuts, so if you are using media keys like how you use normally, you are all good !

https://github.com/EragonJ/Kaku/blob/d9dfab6bcafe8e2434e269ff9dac505fdf300c3f/bootup.js#L70

**Comment by EragonJ** [comment]
This reminds that it would be cool to have a `?` shortcut or `help` menuItem to trigger a popup dialog to list down these things. Can keep this open first and waiting for any other ideas for now.

**Comment by funilrys** [comment]
I this #431 complement this issue.

**Comment by EragonJ** [comment]
close old issue and will open a new one if needed.
