### ISSUE TITLE
Drop-down on Settings Page show black background. hard to read

### ISSUE THREAD

**Issue by shanmukhateja** [EragonJ/Kaku#428]
#### Bug

Clicking on any of the drop-down settings like "Default Language", "Default Top Rating", etc. gives black color in the drop down making it hard to change that property. 

#### Steps to reproduce the bug

1. Open Kaku.
2. Head over to Settings option.
3. Click on any of the drop-down style option like "Default Language", "Default Top Rating".
4. You'll see a black background.

#### What is your Kaku version ?

1.7.0

#### What is your OS with version number ?

Ubuntu Trusty (14.04) x64

#### Which platform you are using to listen to music ?

YouTube

#### Which track format you are using ?

best video mode

#### Is there any error coming from Inspector ?

Hard to check Inspector as it shows no text. It's just plain white pane. Although when mouse is hovered, regular Inspector activity is visible like the blue highlighting of objects. 

#### Screenshot

![s1](https://cloud.githubusercontent.com/assets/5269580/18237330/90cecda2-734d-11e6-9f3c-24691592649f.png)

**Comment by EragonJ** [comment]
I think this may be part of electron issue, some related information - https://github.com/electron/electron/issues/4322
