### ISSUE TITLE
Provide an AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [EragonJ/Kaku#430]
[AppImage](http://appimage.org/) is a format for portable, distribution-agnostic binary software deployment for Linux without needing root permissions or installation. ([Wikipedia](https://en.wikipedia.org/wiki/AppImage_%28packaging_method%29))

Here is an example for Atom in AppImage format:
https://bintray.com/probono/AppImages/Atom/_latestVersion#files

Since this project is using `electron-builder` it is really easy to produce an AppImage; in fact, it is the default format for Linux in the latest electron-builder version.

It would be great if you could provide an AppImage for Linux.

**Comment by EragonJ** [comment]
sure thanks @probonopd , I just rewrote the whole build script from `electron-packager` to `electron-builder` in last few days. In the following releases, AppImage will be used !

I'll close this one first and tell you about how things going after next release, thanks !!

**Comment by EragonJ** [comment]
After thinking a while, i'll keep this issue open until next version got released. :)

**Comment by EragonJ** [comment]
@probonopd Just released 1.8.0 and this is the only format that we support for linux users for now ! (Whooo) Thanks for telling me AppImage ! I already tested that on Ubuntu !
