### ISSUE TITLE
System keyboard shortcuts

### ISSUE THREAD

**Issue by spajdo** [EragonJ/Kaku#431]
Please add support for Sound and Media keyboard shortcuts. For previous/next track and play/pause buttons. It realy miss me.

**Comment by EragonJ** [comment]
@spajdo it's supported natively by Kaku itself already, please check https://github.com/EragonJ/Kaku/blob/d9dfab6bcafe8e2434e269ff9dac505fdf300c3f/bootup.js#L70

**Comment by EragonJ** [comment]
If you found that this doesn't work in your platform / OS, please follow the default format to report your issue here and we'll see how to solve that. Instead, if the comment above does help you, i'll lose this one, thanks :)

**Comment by spajdo** [comment]
#### Bug

I don't have media buttons on my keyboard and therefore I mapped my own shortcuts to controll media players in my system. All players works with this, but Kaku don't work.

#### What is your Kaku version ?

1.5.0

#### What is your OS with version number ?

Ubuntu Gnome 16.04

#### Which platform you are using to listen to music ?

YouTube

#### Which track format you are using ?

best video (or best audio)


Please look at this. This is very useful and nice application and only this miss me. Thank you.

**Comment by EragonJ** [comment]
@spajdo oh that's interesting scenario ... can you try to use 1.7.0 and see how it works for you ?

**Comment by spajdo** [comment]
In 1.7.0 version is the same.
I send you my shortcuts settings.
In Nuvolaplayer (which I use for google play music) it works fine. I think nuvola is too opensource. Maybe try look at his codes.

![screenshot from 2016-09-06 09-46-54](https://cloud.githubusercontent.com/assets/7231035/18265617/e3471f34-7416-11e6-820f-9fb55f453acf.png)

**Comment by EragonJ** [comment]
cool thanks @spajdo I checked electron's source code and it seems that they directly read the keyChart you pressed from your keyboard. So take `play` for example, i think it'll recognize there is one `shift+ctrl+space` got pressed instead of `MediaPlayPause`. 

Let's keep this open first :)

**Comment by EragonJ** [comment]
I'll close this outdated issue first and feel free to reopen if there is any way to bypass this in electron.

**Comment by acrisci** [comment]
The way to make media keys work on Ubuntu and most other Linux distributions is to implement the [MPRIS DBus Specification](https://specifications.freedesktop.org/mpris-spec/latest/).

There's a library for that called [mpris-service](https://github.com/dbusjs/mpris-service).

You can see a list of implementations [here](https://github.com/dbusjs/mpris-service/issues/30).

**Comment by EragonJ** [comment]
@acrisci thanks i'll give it a look
