### ISSUE TITLE
Kaku is broken under Arch Linux (Potential Solution? maybe...)

### ISSUE THREAD

**Issue by BigEars431** [EragonJ/Kaku#433]
#### Bug

When Kaku media player is launched it hangs. It's just a gray window

#### Steps to reproduce the bug

1. Install Arch Linux (An easy way is via "Antergos")
2. Update all packages (sudo pacman -Syyu)
3. Download Kaku for Linux
4. Extract and run binary
5. Gray window of dissapointment

***Might be a library error
***Also reported in the kaku-bin AUR package

#### What is your Kaku version ?

1.7.0

#### What is your OS with version number ?

Arch Linux - Rolling release (Linux localhost431 4.7.2-1-zen #1 ZEN SMP)

#### Which platform you are using to listen to music ?

Unable to use Kaku to listen to music YET =)

#### Which track format you are using ?

N/A

#### Is there any error coming from Inspector ?

N/A

#### Others

This app seems very interesting, hope you guys get it rolling on Arch Linux, or better yet make a snap package or an AppImage for Kaku =))

http://snapcraft.io/
http://appimage.org/

That might get rid of library issues

**Comment by EragonJ** [comment]
hi @BigEars431 , this is the dup of #421, so close this first. Later we'll have AppImage format for linux since next release, so that should be fixed i hope ;)
