### ISSUE TITLE
How to disable video playback?

### ISSUE THREAD

**Issue by tylerecouture** [EragonJ/Kaku#434]
Came here from http://www.omgubuntu.co.uk/2016/09/try-kaku-open-source-desktop-youtube-player

It mentions you can disable video playback, but I don't see that in the Settings (Linux Mint 17.3)

Looks cool and I hope to install it in my highschool classroom! Thank you!

**Comment by EragonJ** [comment]
@tylerecouture you should choose `best audio` in settings panel and you are all done !

**Comment by tylerecouture** [comment]
Thanks!

**Comment by EragonJ** [comment]
:)
