### ISSUE TITLE
can we get a bandcamp.com plugin?

### ISSUE THREAD

**Issue by chovy** [EragonJ/Kaku#435]
bandcamp.com lets you listen to tracks for free.

**Comment by EragonJ** [comment]
@chovy yes that's possible. But right now there is no way to judge which service should be supported because there are too many related services online. hmmm

**Comment by lickedcity** [comment]
in what way is bandcamp and soundcloud in terms of service related? their content has a very different aesthetic. How would a plugin be created?

**Comment by EragonJ** [comment]
close old issue and will open a new one if needed.
