### ISSUE TITLE
Support other platform's list

### ISSUE THREAD

**Issue by yogeshg** [EragonJ/Kaku#439]
It would be nice to have music lists -- such as youtube playlists, spotify playlists, generic text file, from which Kaku can search all its sources

**Comment by EragonJ** [comment]
We do support YouTube playlist if you check settings panel

**Comment by EragonJ** [comment]
Changed this topic to support different platform's playlist because right now we do support YouTube playlist already.

**Comment by yogeshg** [comment]
It'll be nice to have a unified list format, where one can add any cross platform lists

**Comment by EragonJ** [comment]
i can't understand ? can you address more ?

**Comment by yogeshg** [comment]
I noticed how one can play songs from different sources, it'll be nice to have a cross platform playlist, users could create or share these.

**Comment by EragonJ** [comment]
close old issue and will open a new one if needed.
