### ISSUE TITLE
Mixcloud support.

### ISSUE THREAD

**Issue by DWiechert** [EragonJ/Kaku#444]
Is it possible to add support for [Mixcloud](https://www.mixcloud.com/)?

**Comment by EragonJ** [comment]
yes it's possible !

**Comment by DWiechert** [comment]
That's good news.

Should I log another issue is kaku-core for Mixcloud support as well?

**Comment by EragonJ** [comment]
it's fine to put the issue here :)

**Comment by EragonJ** [comment]
We already implemented this feature few weeks ago ! thanks @neighborhood999 !! this feature will be there in 1.9.0!! can't wait to ship i!
