### ISSUE TITLE
Contribution difficulty

### ISSUE THREAD

**Issue by Ethenyl** [EragonJ/Kaku#445]
Hi @EragonJ ,

I would like to contribute to the project but the setup is proving to be quite difficult.

I retrieved the source code from a fork, updated Node & npm to the latest versions, installed my SSH key to allow Github source retrieval.

But I'm still getting an error when running `npm i` :

`npm ERR! Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.`

Any idea ?

Thanks in advance.

**Comment by EragonJ** [comment]
@Ethenyl does google help you for this part  ? like this - https://github.com/brianmcd/contextify/issues/188#issuecomment-240538682

BTW, can you paste the full error log here ? 
BTW2, I updated the docs in wiki here - https://github.com/EragonJ/Kaku/wiki

**Comment by EragonJ** [comment]
@Ethenyl Anything that we can help here :) ?

**Comment by EragonJ** [comment]
@Ethenyl feel free to re-open this issue again if you still have the same problem when trying to contribute things back to Kaku, thanks :)
