### ISSUE TITLE
SH script to create desktop icon.

### ISSUE THREAD

**Issue by SkyzohKey** [EragonJ/Kaku#446]
Hey guys, I really like your application and wanted to have an icon on my desktop for quick-launching it, so I made the following script, maybe you'd like to add it to your release tarballs.

```
File: create-desktop-icon.sh
```
```bash
#!/usr/bin/bash

###
# Desktop icon maker for Kaku music player.
# @author SkyzohKey
# @license MIT
###

# Lets store the current path script is ran.
DIR=$(pwd)

# Store some informations for later usage.
APP_NAME="Kaku"
APP_DESCRIPTION="The next generation music client http://kaku.rocks"
APP_VERSION="1.7.0"
APP_CATEGORIES="Application;Music;"

# Define the file paths for easier configuration.
DESKTOP_FILE="${APP_NAME}.desktop"
LAUNCH_FILE="${APP_NAME}.sh"
LOGO_FILE="logo.png"

# Lets create our simple start script.
echo "# Set the working directory" > "$LAUNCH_FILE"
echo "DIR=\$(pwd)" >> "$LAUNCH_FILE"
echo "" >> "$LAUNCH_FILE"
echo "# Run the application" >> "$LAUNCH_FILE"
echo "cd \$DIR" >> "$LAUNCH_FILE"
echo "./${APP_NAME}" >> "$LAUNCH_FILE"

# Make it executable.
chmod +x "$LAUNCH_FILE"

# Lets create the desktop file.
echo "[Desktop Entry]" > "$DESKTOP_FILE"
echo "Encoding=UTF-8" >> "$DESKTOP_FILE"
echo "Name=${APP_NAME}" >> "$DESKTOP_FILE"
echo "Comment=${APP_DESCRIPTION}" >> "$DESKTOP_FILE"
echo "Path=${DIR}" >> "$DESKTOP_FILE"
echo "Exec=${DIR}/${LAUNCH_FILE}" >> "$DESKTOP_FILE"
echo "Icon=${DIR}/${LOGO_FILE}" >> "$DESKTOP_FILE"
echo "Categories=${APP_CATEGORIES}" >> "$DESKTOP_FILE"
echo "Version=${APP_VERSION}" >> "$DESKTOP_FILE"
echo "Type=Application" >> "$DESKTOP_FILE"
echo "Terminal=0" >> "$DESKTOP_FILE"

# Make it executable and move it to the user xdg-desktop.
chmod +x "$DESKTOP_FILE"
mv "$DESKTOP_FILE" "$(xdg-user-dir DESKTOP)/${DESKTOP_FILE}"

exit 0
```

My two cents.  
I know that issues are not the place for this, but i was really lazy to make a PR. Shame on me, yeah 🐫 

**EDIT**: I just updated the script, allows u to customize it a bit more.

**Comment by EragonJ** [comment]
@SkyzohKey I am not good at linux, so here comes some dumb questions.

1. Where should I put this script into Kaku for linux users ?
2. In the following releases, i'll release `AppImage` format for linux users ( http://appimage.org/), with this, does it help to support the same thing that what your script does ? 

Thanks for the script by the way :)

**Comment by SkyzohKey** [comment]
@EragonJ Heya, this is a bash script, sort of .bat-like on Windoesn't.

To answer your (not so dumb) questions:

1. You simply have to put it at the release root (`dist/OS-Arch-bla/` folder), then Linux guys just have to chmod it and run to enjoy a swag icon on their desktop. (`chmod +x create-desktop-icon.sh; ./create-desktop-icon.sh`)
2. AppImage is sort of .exe, but that's not working the same way. An appimage file is an iso-like file that will be mounted on the filesystem in order to execute the app contained into, unpacking the app's resources too. So yes, if user put that file on its desktop, that's pretty much the same, except that they won't have an icon (iirc appimages doesn't supports icons yet).

Anyway, I'm also a software developer and if you need help with AppImage, I can redirect you to [that script](https://github.com/RicinApp/Ricin/blob/5d2d4c22c06d0e677e8493199a634171fb63bffe/appimage.sh), which was made by @probonopd who is the lead dev of AppImage. The main point of this script is to allow me having an appimage for every Travis-CI build. :)

Again, thanks for that super cool software you made :)

**Comment by EragonJ** [comment]
@SkyzohKey cooool, thanks for providing these information here, i'll add the script to root folder for linux build. And thanks for telling me details about AppImage thing :P
