### ISSUE TITLE
Shuffle mode

### ISSUE THREAD

**Issue by Lucidiot** [EragonJ/Kaku#447]
I'm one of those people using shuffle mode on YouTube playlists, so why not having one on Kaku?

**Comment by EragonJ** [comment]
If you are talking about playing tracks randomly, then that feature already got implemented last week and will be there in next release. If not, please comment down more details about what is shuffle mode in Youtube playlist ?

**Comment by EragonJ** [comment]
^ @Lucidiot

**Comment by Lucidiot** [comment]
I looked for it but couldn't see it, sorry then! Closing down and thanks. :)

**Comment by EragonJ** [comment]
cool thanks !

**Comment by ebadi** [comment]
I downloaded Kaku-1.8.0-x86_64.AppImage but I cannot find this feature. @EragonJ
