### ISSUE TITLE
Shuffle playlist

### ISSUE THREAD

**Issue by MaestroZ** [EragonJ/Kaku#448]
Hi,

I know this isn't a bug as such but is there any way to shuffle a playlist rather than playing tracks in the order they were added?
I'm using the latest version

Thanx for the great job
MaestroZ

**Comment by EragonJ** [comment]
dup of https://github.com/EragonJ/Kaku/issues/447

it's been implemented in source code and will be there in next milestone :)

**Comment by ebadi** [comment]
I downloaded Kaku-1.8.0-x86_64.AppImage but I cannot find this feature. @EragonJ
