### ISSUE TITLE
Kaku/index.html Doesn't exist

### ISSUE THREAD

**Issue by mimi89999** [EragonJ/Kaku#449]
#### Bug
Kaku from the repo doesn't work. Only a blank window opens. In logs Kaku complains, that it can't open index.html. There is no such file in the Kaku directory. 

#### Steps to reproduce the bug

Euh? Run Kaku from the repo?

#### What is your Kaku version ?

Latest commit: 23a70bbe66bf41d868b0cb27dad87bd92e231d81

#### What is your OS with version number ?

Linux debian 4.6.0-1-amd64 Stretch.

#### Which platform you are using to listen to music ?

YouTube (but not important in that issue)

#### Which track format you are using ?

or best audio (but not important in that issue)

#### Is there any error coming from Inspector ?

Not allowed to load local resource: file:///home/michel/git/Kaku/index.html

Blank window.

**Comment by EragonJ** [comment]
thanks for finding that ! I'll provide a quick patch for it in 10 mins.

**Comment by EragonJ** [comment]
@mimi89999 it's a regression when i was trying to rewrite the whole build system. Please update your repo to latest master and give it a try ! Hope you can be one of the contributor for linux branch, big thanks !

**Comment by mimi89999** [comment]
Thanks
