### ISSUE TITLE
Autoplay in playlists

### ISSUE THREAD

**Issue by Lucidiot** [EragonJ/Kaku#450]
As in YouTube, WMP, VLC, Spotify, etc. playlists, why not continue playing the playlist (if not in repeat-one of course) when selecting any video from a playlist ? Like starting the playlist at the selected point.

**Comment by EragonJ** [comment]
it's on my personal TODO list for a long while but I am still doing refactoring works for building process, codes and other new features.

Will go back to this issue when I have time.

**Comment by EragonJ** [comment]
we already came up with `play queue` design so users can add tracks to that queue and do this there.
