### ISSUE TITLE
Can Kaku run in the browser ?

### ISSUE THREAD

**Issue by fredhampton** [EragonJ/Kaku#454]
Can Kaku run in the browser ?
If so what is the port number ?
Is there a way to have Kaku as  node module ?

**Comment by mimi89999** [comment]
No, it can't run in the browser.

**Comment by fredhampton** [comment]
is the app using electron ?

On September 27, 2016 at 11:51:24 AM, Michel Le Bihan (notifications@github.com) wrote:

No, it can't run in the browser.

**Comment by mimi89999** [comment]
Yes

**Comment by fredhampton** [comment]
When the application starts what port it is using on localhost ?


On September 27, 2016 at 12:30:27 PM, Michel Le Bihan (notifications@github.com) wrote:

Yes

**Comment by mimi89999** [comment]
Euh? Isn't it executed directly in Electron?

**Comment by fredhampton** [comment]
electron is a web app wrapper. i m assuming that since this is the case that Kaku is running at localhost:xxxx where xxxx is the port number 


On September 27, 2016 at 12:45:01 PM, Michel Le Bihan (notifications@github.com) wrote:

Euh? Isn't it executed directly in Electron?

**Comment by EragonJ** [comment]
Kaku is bundled with Electron for now, so if you want to run that from browser, you may need to make a custom fork and remove the dependencies with Electron. It's doable because only a few things are bundled with Electron.

**Comment by fredhampton** [comment]
Thanks !!!!
Do you know what port Kaku is running on ?


On September 27, 2016 at 9:37:52 PM, Chia-Lung, Chen (notifications@github.com) wrote:

Kaku is bundled with Electron for now, so if you want to run that from browser, you may need to make a custom fork and remove the dependencies with Electron. It's doable because only a few things are bundled with Electron.

**Comment by EragonJ** [comment]
> Thanks !!!!
> Do you know what port Kaku is running on ?

?? there is no port using when running Kaku.

**Comment by funilrys** [comment]
The defaut port for electron is actually 9000 @fredhampton

**Comment by EragonJ** [comment]
let me close this issue first and if you guys have any questions about it, feel free to file a new one again.
