### ISSUE TITLE
Can't see the options under settings tab.

### ISSUE THREAD

**Issue by Jebiel** [EragonJ/Kaku#457]
#### Bug

Under settings, when I try to change language or other settings the options are all blacked out.

#### What is your Kaku version ?

1.7.0

#### What is your OS with version number ?

Korora 24(Sheldon) 64-bit

#### Which platform you are using to listen to music ?

YouTube

#### Which track format you are using ?

I'm using the option to use best audio

#### Screenshot

![skaermbillede fra 2016-10-07 17-15-40](https://cloud.githubusercontent.com/assets/22646197/19195583/79c34eac-8cb2-11e6-9773-655b6b260dc0.png)

#### Others

Another question while i'm at it, I just completed the Danish language on transifex, is it possible to push an update 1.7.1 with the newest languages?

Besides that I'm a big fan of Kaku, keep up the good work!

**Comment by EragonJ** [comment]
1. this should be fixed in next release. feel free to give it a try later.
2. I'll try to release 1.8.0 with newest languages and this fix.

Because this issue should be fixed by one commit I made few weeks ago, so close first and feel free to re-open if it's not working. Thanks !
