### ISSUE TITLE
Error when making "backup data to local" file system

### ISSUE THREAD

**Issue by ebadi** [EragonJ/Kaku#460]
#### Bug

Backup data to local doesn't work on Linux machine (Ubuntu 14.04). Note that the option to store on dropbox works fine. 
Feature request:
The current backup solution is not useful without an import backup feature. 
It would be nice to have an option to backup all playlists from a plaintext file (.cvs) when you close down the application and possible load them again from the same file on startup. Plaintext files are easy to store in git and other version controlling systems and light to transfer between clients (e.g. home and work PC). 

#### What is your Kaku version ?

1.7.0

#### What is your OS with version number ?

Ubuntu 14.04

#### Is there any error coming from Inspector ?

![kaku](https://cloud.githubusercontent.com/assets/1111940/19416822/c85136a8-939a-11e6-8c6f-29f82b95b3b0.png)

**Comment by EragonJ** [comment]
I already fixed this few weeks ago, will be fixed in 1.8.0 so i am closing this issue for now. If this doesn't work, feel free to re-open again, thanks @ebadi
