### ISSUE TITLE
No video playback youtube

### ISSUE THREAD

**Issue by Kingbalou** [EragonJ/Kaku#463]
#### Bug

When i choose a video from my search in youtube, i don't see the video on the player.
#### Steps to reproduce the bug

mmmh .. Search a video like `hardstyle 2016`
#### What is your Kaku version ?

1.7.0
#### What is your OS with version number ?

Windows 10
#### Which platform you are using to listen to music ?

YouTube
#### Which track format you are using ?

best video || best audio
Tested both of them
#### Is there any error coming from Inspector ?

![image](https://cloud.githubusercontent.com/assets/6079068/19592373/b3841652-977b-11e6-94b4-3e01d1fb1ad4.png)
#### Others

Feel free to point out any missing points here :) thanks !

**Comment by EragonJ** [comment]
@Kingbalou how about update the player from settings panel and try again ? Does it help ? I can't reproduce that here in my side, which youtube video did you play ?

**Comment by Kingbalou** [comment]
Yep already tried , and download a new version of kaku

**Comment by EragonJ** [comment]
@Kingbalou ok plz help me to give it a try later when 1.8.0 got released. thx.

**Comment by Kingbalou** [comment]
Do you have some ETA for 1.8.0 release ?

**Comment by EragonJ** [comment]
@Kingbalou within 2 weeks (or this week i think). too many daily works to do here in my side :S

**Comment by Kingbalou** [comment]
Okey no prob ;) GL

**Comment by Kingbalou** [comment]
Still no luck with 1.8.0 release :/

**Comment by EragonJ** [comment]
lol i didn't get it, so this is solved or not ~?

**Comment by Kingbalou** [comment]
Yep solved !

**Comment by EragonJ** [comment]
cool ok ! thanks :)

**Comment by CorentinDy** [comment]
Hi, back with the same error .. :/ fresh install on new pc and i've had video playback on 1 or 2 videos and now nothing
