### ISSUE TITLE
Online DJ / Chat room not working

### ISSUE THREAD

**Issue by Kingbalou** [EragonJ/Kaku#465]
#### Bug

I wanted to became a DJ ! But Kaku knows that i'm a bad dj .. 

#### Steps to reproduce the bug

Click on become a DJ with pseudo and chan name then create a chan

#### What is your Kaku version ?

1.8.0

#### What is your OS with version number ?

Windows 10 x64

#### Which platform you are using to listen to music ?

All

#### Which track format you are using ?

best video

#### Is there any error coming from Inspector ?

![image](https://cloud.githubusercontent.com/assets/6079068/20092356/fe52e9ae-a597-11e6-987c-227cfc4ccff0.png)

#### Others

Feel free to point out any missing points here :) thanks !

**Comment by EragonJ** [comment]
@Kingbalou my bad ... thanks for reporting the issue, i already figured out the problems. I'll make a new release later when I refactor online DJ feature. Sorry about that :S

**Comment by EragonJ** [comment]
already fixed.
