### ISSUE TITLE
How do I open Kaku 1.8 on Ubuntu?

### ISSUE THREAD

**Issue by sagarr** [EragonJ/Kaku#467]
#### Bug

AppImage not opening on Ubuntu

#### What is your Kaku version ?

1.8

#### What is your OS with version number ?

Ubuntu 14.04

**Comment by mimi89999** [comment]
@sagarr 
> AppImage not opening on Ubuntu

Could you explain?

**Comment by neighborhood999** [comment]
@sagarr `chmod a+x Kaku-1.8.0-x86_64.AppImage`

**Comment by sagarr** [comment]
@neighborhood999  thanks, it solved the problem
