### ISSUE TITLE
Unable To Create Room Under Online DJ

### ISSUE THREAD

**Issue by solancer** [EragonJ/Kaku#470]
#### Bug

Please describe the bug you found here !
Unable create room under Online DJ

#### Steps to reproduce the bug
Try Creating a new room under Online DJ

#### What is your Kaku version ?
1.8.0

#### What is your OS with version number ?
Mac OSX 10.12.1

#### Which platform you are using to listen to music ?
NA

#### Which track format you are using ?
NA

#### Is there any error coming from Inspector ?
![Error Console](http://i.imgur.com/ViO2Kx8.png)

#### Others

Feel free to point out any missing points here :) thanks !

**Comment by EragonJ** [comment]
hey thanks @solancer , this is an known issue and will be fixed in next release. Thanks and feel free to drop any issue you found here.

**Comment by EragonJ** [comment]
fixed in 1.8.5
