### ISSUE TITLE
Can't install npm modules

### ISSUE THREAD

**Issue by mimi89999** [EragonJ/Kaku#476]
#### Bug

`npm i` fails on freshly cloned Kaku.

> michel@debian:~/git/Kaku$ npm i
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm ERR! git clone git@github.com:github:eragonj/dropbox-sdk-js Clonage dans le dépôt nu '/home/michel/.npm/_git-remotes/git-github-com-github-eragonj-dropbox-sdk-js-9f509e2a'
npm ERR! git clone git@github.com:github:eragonj/dropbox-sdk-js fatal: remote error: 
npm ERR! git clone git@github.com:github:eragonj/dropbox-sdk-js    is not a valid repository name
npm ERR! git clone git@github.com:github:eragonj/dropbox-sdk-js   Email support@github.com for help
npm ERR! notarget No compatible version found: dropbox@'github:eragonj/dropbox-sdk-js'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.3.0","0.3.1","0.3.2","0.3.3","0.3.4","0.3.5","0.4.0","0.5.0","0.6.0","0.6.1","0.6.2","0.6.3","0.7.0","0.7.1","0.7.2","0.8.0","0.8.1","0.8.2","0.9.0","0.9.1-beta1","0.9.1-beta2","0.9.1","0.9.2","0.10.0","0.10.1","0.10.2","0.10.3","2.0.0","2.1.0","2.2.1","2.3.0","2.4.0","2.5.0"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

> npm ERR! System Linux 4.8.13-gnu
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "i"
npm ERR! cwd /home/michel/git/Kaku
npm ERR! node -v v4.6.1
npm ERR! npm -v 1.4.21
npm ERR! code ETARGET
npm ERR! git clone git@github.com:github:eragonj/youtube-node Clonage dans le dépôt nu '/home/michel/.npm/_git-remotes/git-github-com-github-eragonj-youtube-node-ab1d4a62'
npm ERR! git clone git@github.com:github:eragonj/youtube-node fatal: remote error: 
npm ERR! git clone git@github.com:github:eragonj/youtube-node    is not a valid repository name
npm ERR! git clone git@github.com:github:eragonj/youtube-node   Email support@github.com for help
npm ERR! git clone git@github.com:github:eragonj/node-youtube-dl Clonage dans le dépôt nu '/home/michel/.npm/_git-remotes/git-github-com-github-eragonj-node-youtube-dl-0413c996'
npm ERR! git clone git@github.com:github:eragonj/node-youtube-dl fatal: remote error: 
npm ERR! git clone git@github.com:github:eragonj/node-youtube-dl    is not a valid repository name
npm ERR! git clone git@github.com:github:eragonj/node-youtube-dl   Email support@github.com for help
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/michel/git/Kaku/npm-debug.log
npm ERR! not ok code 0

#### What is your Kaku version ?

6afe9f7d45aae92c6168877d26a60e81970a7387

#### What is your OS with version number ?

Linux debian 4.8.13-gnu #1 SMP Fri Dec 9 01:47:16 UTC 2016 x86_64 GNU/Linux

**Comment by EragonJ** [comment]
@mimi89999 can you attach your `npm-debug.log` ? and by the way, can you try to use nvm and change your version to : `Now using node v5.1.1 (npm v2.15.6)` ? This is what I used to develop.

And also, how about use `npm install` twice and see how the problem is going ?

**Comment by mimi89999** [comment]
@EragonJ I managed to fix it. I run `sudo npm install npm -g` and now I have `npm 4.0.5` and `node v4.6.1` (didn't update node). It works now.
