### ISSUE TITLE
Dev YouTube API key doesn't work

### ISSUE THREAD

**Issue by mimi89999** [EragonJ/Kaku#481]
@EragonJ 
Songs won't play. Getting 403 responses from YouTube API with that message:
> Project 180988081892 has been scheduled for deletion and cannot be used for API calls. Visit https://console.developers.google.com/iam-admin/projects?pendingDeletion=true to undelete the project.

**Comment by EragonJ** [comment]
should be fixed by https://github.com/EragonJ/Kaku/commit/abb7fe74d40859624bb1451300c038db26917f0a
