### ISSUE TITLE
Can't play anything

### ISSUE THREAD

**Issue by Kingbalou** [EragonJ/Kaku#482]
#### Bug

Can't play any youtube video

#### Steps to reproduce the bug

search and play a youtube video

#### What is your Kaku version ?

1.8.5

#### What is your OS with version number ?

W10 Pro

#### Which platform you are using to listen to music ?

YouTube 

#### Which track format you are using ?

both

#### Is there any error coming from Inspector ?

![image](https://cloud.githubusercontent.com/assets/6079068/22416378/82e0c336-e6ce-11e6-8909-c54e4cb540aa.png)

#### Others

Did a fresh install before reporting bug and same issue

**Comment by EragonJ** [comment]
@Kingbalou did you try to `update player` in settings page ?

**Comment by Kingbalou** [comment]
Yes i tried and it change nothing

**Comment by EragonJ** [comment]
but when i click `update player` then it works, not sure what's the problem there in your case hmm, anyway, if you can find any solution for it, just paste here, thanks.

**Comment by Kingbalou** [comment]
Ok, so i did a fresh install of kaku by uninstalling and deleting all votatile files and now it works, don't why .. but it's okey since a week now

**Comment by EragonJ** [comment]
@Kingbalou great, then i'll close this issue for now. Thanks !!
