### ISSUE TITLE
Add an option to disable chatroom

### ISSUE THREAD

**Issue by LittleWhite-tb** [EragonJ/Kaku#491]
I noticed the little chatroom stuff at the bottom right of Kaku. I would like to be able to remove it completely. My points are :
- I don't want the chat and since, I find it annoying to have it there 
- I don't want Kaku to have any chat functionalities (I find it useless) and so I would like to remove it to free up some memory/CPU
- I don't even know to what it is connecting and it is always at 0 people connected

Thanks

**Comment by funilrys** [comment]
:+1: 
People should have the choice @EragonJ :wink:

**Comment by EragonJ** [comment]
lol
