### ISSUE TITLE
Play All button does not seem to do anything

### ISSUE THREAD

**Issue by LittleWhite-tb** [EragonJ/Kaku#492]
#### Bug

The Play All button does not seem to work.

#### Steps to reproduce the bug

I have created a new playlist. I filled it with some songs/videos (from Youtube). I am opening the playlist and clicking on "Play All". It does not play anything.

#### What is your Kaku version?

1.8.5

#### What is your OS (with version number)?

Windows
Manjaro Linux  - 4.4.52
(My bug is not the same as #489, since I can reproduce it on Windows)

#### Which platform are you using to listen to music?

YouTube

#### Which track format are you using?

best video

**Comment by funilrys** [comment]
please report to #489

**Comment by LittleWhite-tb** [comment]
On Windows, even if "Play All" didn't work, music could be played normally (by filling the play queue with songs from my playlist) and then playing on of these songs.
I suppose I did not get what the "Play All" button is supposed to do.

**Comment by funilrys** [comment]
Can you give us a screenshot of the inspector under the console tab ?

**Comment by LittleWhite-tb** [comment]
The two errors are related to #489. When clicking on "Play All", nothing happens.

![kaku_492](https://cloud.githubusercontent.com/assets/8618754/23966295/12a75bec-09bb-11e7-8576-a13f46871614.png)

Tomorrow, I should be able to redo this test on Windows.

**Comment by funilrys** [comment]
Okay the screenshot => #489 
Interesting if windows have the same behavior...

**Comment by neighborhood999** [comment]
@LittleWhite-tb In personal playlist, play all button already fixed. see #483

**Comment by EragonJ** [comment]
ok that should be fixed in 1.9.0. I think i'll take some time to release the new version.

**Comment by LittleWhite-tb** [comment]
Cool.
You can put this as duplicate of #478
