### ISSUE TITLE
[Windows] Song stops to play when I right click and contextual menu show up

### ISSUE THREAD

**Issue by LittleWhite-tb** [EragonJ/Kaku#493]
#### Bug

The music currently playing stops after 2 or 3 seconds when the contextual menu show up (right click on playlist, or on song)

#### Steps to reproduce the bug

Start to play a song. Enjoy the song. Do a right click that open up a contextual menu (i.e. right click on one of your playlist). Songs stops to play after 2/3 seconds.

#### What is your Kaku version?

1.8.5

#### What is your OS (with version number)?

Windows 10

#### Which platform are you using to listen to music?

YouTube

#### Which track format are you using?

Best audio (same with best video)

**Comment by EragonJ** [comment]
ok it's kinda weird and i can reproduce it now, i'll check it, thanks.

**Comment by Waffeldrache** [comment]
I can also confirm this behavoir on Arch Linux as well.

**Comment by EragonJ** [comment]
thasnk @LittleWhite-tb @Waffeldrache , this is an issue in electron, already provided a patch for it.
