### ISSUE TITLE
[IMPORTANT] Maintainers Needed

### ISSUE THREAD

**Issue by EragonJ** [EragonJ/Kaku#495]
For some personal reasons (lie, I have too many projects undergoing so I can't contribute like what I did before to Kaku), I am looking for collaborators / maintainers for Kaku!

In my mind, Kaku can be a better open sourced media player in all platforms, so I think this project is still worth to work on and I am sure it can benefit tons of users (including you!).

If you are interested in maintaining this project and know how to write JavaScript / HTML / CSS, feel free to drop me a message (or simply comment down below), I'll add you into collaborator list. 

Big thanks :)

**Comment by EragonJ** [comment]
BTW, your avatar will be shown on http://kaku.rocks :P

**Comment by funilrys** [comment]
Tell me if it's the wrong place ... 

I think it'll be great to add somewhere that we (collaborator and contributors) **need to work on branch then PR, review by other and merge**.
I just worked with non-git speaker and they just created some unexcepted bigs which could me avoid with
_work on branch then PR, review by other and merge_  ...

**Comment by EragonJ** [comment]
@funilrys i think maybe we can treat master as a stable branch and open a new branch name with next milestone (1.9.6 for example), and people keep adding features into that branch (if your patch needs an review, then file a new PR based on that branch and mark reviewers, instead, just merge by yourself)

Everyone is responsible for your own patch and don't worry too much about it, we are human beings and sometimes we'll make mistakes, just revert it and try to add more tests to cover them if possible then it will be fine !

@funilrys @neighborhood999 what do you people think ? From my mind, I want to make Kaku more like a autonomous community and every contributor (including me) has the same privilege to decide & change things.

**Comment by Werner1201** [comment]
Man, I know you need mainteiners but I recently tried to translate some things in Portuguese and it didn't get to stay there. Did I do something wrong ?

**Comment by EragonJ** [comment]
hey @Werner1201 , thanks for help! translations will only be merged into codebase before trying to release a new version, otherwise it will make codebase flooded with tons of relevant commit messages. 

I'll merge all the changes from translation soon ! Sorry for making you confused 😐 

While for maintainers, if you are willing to write codes, make some changes to Kaku, it would be nice and I can add you into contributors :)

**Comment by Werner1201** [comment]
Sorry for anwsering this late, I've been occupied. @EragonJ  I noticed you did A huge Update and my contribution wasn't there. I'm not angry or anything, since all I did meaned nothing compared with the addtions of this Huge update but I hope I'll be more faster in the future to translate the next update. I wish a lot of success to you and your app

**Comment by EragonJ** [comment]
@Werner1201 I think that's because you are not following how we do translation, please check https://github.com/EragonJ/Kaku/issues/377#issue-130936113 for reference!

All translators' names will be listed to the repo later when we update translations (we'll write a script to help us grep all names from trasnifex and merge to `thanks.json`)

BTW, I'll make another section on http://kaku.rocks later for all the helps from translators!

Big thanks :)

**Comment by lickedcity** [comment]
Hey – yeah I'd love to be to be a contribute !!
I've been working on the exact project idea, solo.

**Comment by EragonJ** [comment]
@lickedcity thanks! any help is welcome.
