### ISSUE TITLE
The music not playing

### ISSUE THREAD

**Issue by sergiopjf** [EragonJ/Kaku#515]
**Bug**

The music not playing, is loading infinitily.

## **Console Panel Error Message:** (Computer 1**)
```
C:\Users\srmp\AppData\Local\Programs\Kaku\resources\app.asar\node_modules\react-dom\lib\ReactDOM.js:73 Download the React DevTools and use an HTTP server (instead of a file: URL) for a better development experience: https://fb.me/react-devtools
C:\Users\srmp\AppData\Local\Programs\Kaku\resources\app.asar\node_modules\fbjs\lib\warning.js:36 Warning: DashboardPage: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.
printWarning @ C:\Users\srmp\AppData\Local\Programs\Kaku\resources\app.asar\node_modules\fbjs\lib\warning.js:36
C:\Users\srmp\AppData\Local\Programs\Kaku\resources\app.asar\node_modules\fbjs\lib\warning.js:36 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
printWarning @ C:\Users\srmp\AppData\Local\Programs\Kaku\resources\app.asar\node_modules\fbjs\lib\warning.js:36
kaku.bundled.js:2520 found a new update
kaku.bundled.js:264 updated youtube-dl successfully
kaku.bundled.js:2528 update not available
util.js:1022 Uncaught (in promise) Error: spawn UNKNOWN
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:399:9)
    at exports.execFile (child_process.js:160:15)
    at module.(anonymous function) (ELECTRON_ASAR.js:200:20)
    at C:\Users\srmp\AppData\Local\Programs\Kaku\resources\app.asar\node_modules\youtube-dl-node\dist\YoutubeDL.js:50:37
    at YoutubeDL._execCommand (C:\Users\srmp\AppData\Local\Programs\Kaku\resources\app.asar\node_modules\youtube-dl-node\dist\YoutubeDL.js:37:14)
    at YoutubeDL.getInfo (C:\Users\srmp\AppData\Local\Programs\Kaku\resources\app.asar\node_modules\youtube-dl-node\dist\YoutubeDL.js:77:19)
    at TrackInfoFetcher.getInfo (file:///C:/Users/srmp/AppData/Local/Programs/Kaku/resources/app.asar/kaku.bundled.js:773:16)
    at Player._getRealTrack (file:///C:/Users/srmp/AppData/Local/Programs/Kaku/resources/app.asar/kaku.bundled.js:16885:40)
    at file:///C:/Users/srmp/AppData/Local/Programs/Kaku/resources/app.asar/kaku.bundled.js:17007:20
    at process._tickCallback (internal/process/next_tick.js:103:7)
```
**Steps to reproduce the bug**

Click to play any music on top list or search.

**What is your Kaku version?**

1.9.0

**What is your OS (with version number)?**

Windows 10  x64

**Which platform are you using to listen to music?**

All

**Which track format are you using?**

Best video

## **Console Panel Error Message in computer 2 (Windows 10 x64):**
```
Download the React DevTools and use an HTTP server (instead of a file: URL) for a better development experience: https://fb.me/react-devtools
C:\Users\srmp\AppData\Local\Programs\Kaku\resources\app.asar\node_modules\fbjs\lib\warning.js:36 Warning: DashboardPage: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.
printWarning @ C:\Users\srmp\AppData\Local\Programs\Kaku\resources\app.asar\node_modules\fbjs\lib\warning.js:36
C:\Users\srmp\AppData\Local\Programs\Kaku\resources\app.asar\node_modules\fbjs\lib\warning.js:36 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
printWarning @ C:\Users\srmp\AppData\Local\Programs\Kaku\resources\app.asar\node_modules\fbjs\lib\warning.js:36
kaku.bundled.js:2520 found a new update
kaku.bundled.js:264 updated youtube-dl successfully
kaku.bundled.js:2528 update not available
child_process.js:223 Uncaught (in promise) Error: Command failed: C:\Users\srmp\AppData\Roaming\Kaku\youtube-dl --dump-json -f best --no-check-certificate --no-cache-dir -f best https://www.youtube.com/watch?v=72UO0v5ESUo


    at ChildProcess.exithandler (child_process.js:223:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by EragonJ** [comment]
@sergiopjf plz try to click `update player` in settings and try again until it's updated. thanks

**Comment by sergiopjf** [comment]
On the computer 1 worked, but on computer 2 the update don't worked, it's display the following error in the console:

Download the React DevTools and use an HTTP server (instead of a file: URL) for a better development experience: https://fb.me/react-devtools
C:\Users\srmp\AppData\Local\Programs\Kaku\resources\app.asar\node_modules\fbjs\lib\warning.js:36 Warning: DashboardPage: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.
printWarning @ C:\Users\srmp\AppData\Local\Programs\Kaku\resources\app.asar\node_modules\fbjs\lib\warning.js:36
C:\Users\srmp\AppData\Local\Programs\Kaku\resources\app.asar\node_modules\fbjs\lib\warning.js:36 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
printWarning @ C:\Users\srmp\AppData\Local\Programs\Kaku\resources\app.asar\node_modules\fbjs\lib\warning.js:36
kaku.bundled.js:2520 found a new update
kaku.bundled.js:264 updated youtube-dl successfully
kaku.bundled.js:2528 update not available
child_process.js:223 Uncaught (in promise) Error: Command failed: C:\Users\srmp\AppData\Roaming\Kaku\youtube-dl --dump-json -f best --no-check-certificate --no-cache-dir -f best https://www.youtube.com/watch?v=72UO0v5ESUo


    at ChildProcess.exithandler (child_process.js:223:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)

**Comment by EragonJ** [comment]
@sergiopjf i think the problem should be the same based on the error log and the fact that your computer 1 does work.

**Comment by sergiopjf** [comment]
I uninstalled, reinstalled and updated the Kaku on computer 2 and don't worked.

**Comment by sergiopjf** [comment]
I tried on a third computer and it presented the same error of computer 2.

**Comment by EragonJ** [comment]
@sergiopjf can you check `C:\Users\srmp\AppData\Roaming\Kaku\` there should be a `VERSION` file, can you check how new is it ? for mine, it is `2017.06.25`

**Comment by sergiopjf** [comment]
2017.06.27 and after trying update again now 2017.06.29

See attached images
![version](https://user-images.githubusercontent.com/18566003/27670420-22642b28-5c63-11e7-8c0f-588d9ffa395d.png)
![version2](https://user-images.githubusercontent.com/18566003/27670421-22651376-5c63-11e7-98aa-17d7c95401ae.png)

**Comment by EragonJ** [comment]
@sergiopjf no, i mean the content of VERSION file

**Comment by sergiopjf** [comment]
2017.06.25

**Comment by EragonJ** [comment]
@sergiopjf then it should be working. Can you try to use powershell and try to execute `youtube-dl.exe` there ? to make sure it's working well.

**Comment by sergiopjf** [comment]
![image](https://user-images.githubusercontent.com/18566003/27670645-a453aa04-5c64-11e7-9e8d-1a30864520fc.png)

**Comment by EragonJ** [comment]
@sergiopjf you need to add `.\` path to execute it

**Comment by sergiopjf** [comment]
![image](https://user-images.githubusercontent.com/18566003/27670680-ec042928-5c64-11e7-8481-db56951352e4.png)

**Comment by EragonJ** [comment]
@sergiopjf no result ? how about execute `./youtube-dl.exe` only ?

**Comment by sergiopjf** [comment]
No result. Nothing happens after running the command ./youtube-dl.exe only or full.

**Comment by EragonJ** [comment]
@sergiopjf how about you remove the original youtube-dl and replace it with the one from https://yt-dl.org/latest/youtube-dl.exe ?

**Comment by EragonJ** [comment]
I am guessing that there must be something missing when downloading that file in your side

**Comment by sergiopjf** [comment]
Same result

**Comment by EragonJ** [comment]
@sergiopjf after downloading the new youtube-dl, go to kaku and try to play songs and see what's going on there ?

**Comment by sergiopjf** [comment]
![image](https://user-images.githubusercontent.com/18566003/27670936-a8e6ab78-5c66-11e7-88fd-86bd7d927e2b.png)

**Comment by sergiopjf** [comment]
I can send the folder for you to examine.

**Comment by EragonJ** [comment]
i'll check the screenshot & log again, for the time being, plz play it on your pc 1 LOL I need to check some codes later for this.

**Comment by sergiopjf** [comment]
ok, thanks!

**Comment by EragonJ** [comment]
Should be fixed by latest version
