### ISSUE TITLE
[Proposal]Prettier code format

### ISSUE THREAD

**Issue by neighborhood999** [EragonJ/Kaku#517]
I think we can using [Prettier](https://prettier.io/) for code formatting in Kaku.

**Comment by neighborhood999** [comment]
I opened new **lint** branch.

**Comment by neighborhood999** [comment]
[brace-style](http://eslint.org/docs/rules/brace-style)

**Comment by EragonJ** [comment]
@neighborhood999 how's everything :D ?

**Comment by neighborhood999** [comment]
@eragonj Not yet, sorry! 😭

**Comment by neighborhood999** [comment]
I delete branch `lint`. Create new branch follow recently update.

**Comment by EragonJ** [comment]
close old issue and will open a new one if needed.
