### ISSUE TITLE
[Linux] How do you install on ubuntu?

### ISSUE THREAD

**Issue by KoreMike** [EragonJ/Kaku#518]
How do you install on ubuntu?

**Comment by funilrys** [comment]
Please execute in a Terminal 

`dpkg -i Kaku-1.9.0-you-architecture-here.deb` :)

**Comment by funilrys** [comment]
To do: Write instructions into wiki or readme.

**Comment by KoreMike** [comment]
where do I get the deb file?

**Comment by funilrys** [comment]
@KoreMike [there](https://github.com/EragonJ/Kaku/releases/latest)

**Comment by KoreMike** [comment]
Sorry thanks @funilrys don't know how I missed that before!

**Comment by funilrys** [comment]
No problem @KoreMike :smile_cat:

**Comment by EragonJ** [comment]
thanks!
