### ISSUE TITLE
Main window content not loading ("White page issue")

### ISSUE THREAD

**Issue by Fincer** [EragonJ/Kaku#530]
#### Bug

After I have compiled Kaku from source code (GIT version) and trying to launch the program, the main window content is not loading: only white page appears with an everlasting "Loading..." text on the upper left corner.

Picture demonstrating the issue: [Kaku not loading - image](https://i.imgur.com/W160YwB.png)

#### Steps to reproduce the bug

1. Compile from source//Use GIT version
2. Launch the program from main executable

#### What is your Kaku version?

GIT version (Latest commit 38c578b)

#### What is your OS (with version number)?

Arch Linux x86_64

#### Is there any error coming from Inspector?

You can use:
* `ctrl +  alt + i` on **Linux** 

I'm not able to launch inspector (it works in precompiled 1.9.0 version, though)

**Comment by EragonJ** [comment]
@Fincer there are few errors in your screenshot but it was cut. Can you check it and try to fix based on it ?

**Comment by funilrys** [comment]
That's remind me my first noob issue #421 😂😂 Anyway can this be related to the node version ? 🤔

**Comment by funilrys** [comment]
@Fincer did you `cp config/api_config.development.json config/api_config.production.json` ? 🤔

**Comment by Fincer** [comment]
@Eragon

They are just errors I've mentioned [here](https://github.com/EragonJ/Kaku/issues/529). So nothing new in this matter. They are produced by `npm run build:linux`, not `npm install`

@funilrys

Already did `cp config/api_config.development.json config/api_config.production.json`

I am using Node 9.2.0.

Are you able to reproduce the issue with this node version?

-------------------------

I have this outcome with `npm run start`, too (without building linux package).

**Comment by EragonJ** [comment]
Should be fixed in latest version, if not, please file a new one with details, thanks.
