### ISSUE TITLE
Blank White Screen After Drag File Music

### ISSUE THREAD

**Issue by epicedos** [EragonJ/Kaku#531]
#### Expected behavior
Show music list after being added in the Category "Music"  in the application

#### Actual behavior
After I add the folder / music into the playlist menu of the application
the display becomes a blank screen and only displays along with show displays feature play/pause

#### How to reproduce
Run the Application
Create a folder "Music" on the menu "Add playlist"
Drag music from desktop into application
The display becomes a blank screen and only displays along with show displays feature play/pause

- ACER Aspire 4750
-Intel Core i3
- RAM 4 GB
- Operation System Windows 7 Ultimate x64 bit
-Application Version : 1.9.0

#### Recording Of The Bug
https://youtu.be/N_8JeQvsr4w
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@saputra.ridho/blank-white-screen-after-drag-file-music">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by EragonJ** [comment]
hi @epicedos , Kaku is not designed for playing local music since ppl do have their own preferred program like iTunes, foobar ... etc.
