### ISSUE TITLE
Kaku stuck on "Loading"

### ISSUE THREAD

**Issue by filisko** [EragonJ/Kaku#533]
#### Steps to reproduce the bug

I think that it's because I "killed" all the kaku processes (didn't send the SIGNINT signal?). So maybe there is something that should be closed on exit that didn't get close.

#### What is your Kaku version?

1.9.0.1

#### What is your OS (with version number)?

Ubuntu Mate 16.04
Linux 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64

#### Which platform are you using to listen to music?

YouTube

#### Which track format are you using?

best video (or best audio)

#### Is there any error coming from Inspector?

I can't open it.

#### Others

The loader icon even does not move. It starts moving at the beginning but then it just stops, I can't even click on the Minimize/Maximize/Close buttons.
![Image](https://i.imgur.com/KSrgdSp.png)

**Comment by filisko** [comment]
Sorry, yes :smile: It's 1.9.0, I have it on my package manager as 1.9.0-1, and I've got confused

**Comment by funilrys** [comment]
Do you have a link/description/screenshot to the package manager?

I do not remember publishing this to the package manager :thinking:

**Comment by EragonJ** [comment]
close old issue and will open a new one if needed.
