### ISSUE TITLE
feature request: provide appimage version 1.9.0

### ISSUE THREAD

**Issue by Lvaskz** [EragonJ/Kaku#535]
hi, I see kaku 1.9.0 is not as appimage, can you provide one?
Will you provide appimages in the future?

**Comment by EragonJ** [comment]
@funilrys I need you xD we also need to layout a better plan for kaku to make sure it can be a long-term project and hope it can get some donations to make me pay server fees :/

**Comment by funilrys** [comment]
@EragonJ For sure :wink: I did post something into our Slack but it's only a starting point ...

Talking about this issue, If we add AppImage, it's normally impossible to auto update as it's read-only so it'll reintroduce #489

**Comment by hfel** [comment]
Why not use snap or flatpak? It makes installation, desktop integration and updating easier than manual browser downloads, and in enabling updating also surpasses the AppImage format.

**Comment by Lvaskz** [comment]
I think you right. Can you provide one @EragonJ ?

**Comment by funilrys** [comment]
@hfel @Lvaskz will look into it please ping me if I did not answer my opinion here :+1:

**Comment by Lvaskz** [comment]
any progress?

**Comment by EragonJ** [comment]
fixed by 2.0.1 release.
