### ISSUE TITLE
[Enhancement] Add support for Apple Music (through MusicKit JS)

### ISSUE THREAD

**Issue by onigoetz** [EragonJ/Kaku#538]
Hello,

will you consider adding Apple Music support on your application ? 

Apple announced MusicKit JS to embed MusicKit in web apps. (https://developer.apple.com/documentation/musickitjs)
Which to my understanding makes it possible to implement it in an Electron app.

Currently the only way to access Apple Music is on Windows or macOS, but Linux has no viable option.

**Comment by EragonJ** [comment]
hmm worth to give it a try i think

**Comment by EragonJ** [comment]
close old issue and will open a new one if needed.
