### ISSUE TITLE
update electron-builder

### ISSUE THREAD

**Issue by EragonJ** [EragonJ/Kaku#540]
It's been a while not updating Kaku, so need something to start :) Right now it seems that electron-builder is out of date for a while and there must be some important updates recently. In order to make a better support for different OS (including formats that ppl always look for), we should update this first.

**Comment by EragonJ** [comment]
ok this should be fixed by https://github.com/EragonJ/Kaku/commit/34f3e86c0d785cedc3fa8d30813dc8c1544bb121 , will need more tests for it.

@funilrys not sure whether you are still here or not, if yes, right now for every commit, it'll automatically trigger Travis to build everything for the draft version (for now, it is 2.0.0), so you can see latest builds here https://github.com/EragonJ/Kaku/releases/tag/untagged-eb7dc19c94a0e68595bb

If you have time, mind help me check whether everything is working on Linux ? I'll focus more things on Kaku Pro version & Cloud feature soon in the future.

**Comment by funilrys** [comment]
Hi @EragonJ  I'm still (and always) here :smile_cat: 

Will do the test this weekend or in the coming week :+1:
