### ISSUE TITLE
Linux 64 point to Kaku-1.9.0-ia32.tar.gz on website

### ISSUE THREAD

**Issue by nephaste** [EragonJ/Kaku#541]
on Website no generic x64 Linux version and in release on Githug

and on website Linux (64) point to Kaku-1.9.0-ia32.tar.gz 

Kaku-1.9.0-ia64.tar.gz seems missing... 

:(((

**Comment by EragonJ** [comment]
@nephaste sorry I didn't notice this message, I'll fix that later but for now, you can download it directly from here https://github.com/EragonJ/Kaku/releases/tag/1.9.0
