### ISSUE TITLE
literally will not stop loading

### ISSUE THREAD

**Issue by asdfghjkl403622** [EragonJ/Kaku#543]
it stays on the loading screen for the video indefinitely

Please describe the bug you found here!

literally just got it. im using ubuntu bionic beaver LTS.

If you do find a solid way to reproduce this, please write them down here because it can be super useful for debugging!

don't know how to check version, but today is Monday, December 15th

#### What is your OS (with version number)?

ubuntu 18.04 bionic beaver LTS

*Note for Linux Users: Please provide here the result of `name -same`*

#### Which platform are you using to listen to music?

YouTube

#### Which track format are you using?

best video (or best audio)

#### Is there any error coming from Inspector?

You can use:
* `ctrl + alt + i` on **Windows**
* `ctrl +  alt + i` on **Linux** 
* `cmd + option + i` on **Mac**

To turn on `inspector`.

Then switch to the `console` tab and copy the error(s) message(s) you found!
If possible, any screenshot would be better!

#### Others

Feel free to point out any missing points here :) thanks!

**Comment by asdfghjkl403622** [comment]
pls help

**Comment by EragonJ** [comment]
it's hard to debug without logs from the inspector, is it possible to get the screenshot there?

**Comment by asdfghjkl403622** [comment]
I actually fixed it by updating again and restarting, but please look out for bugs like this!

**Comment by asdfghjkl403622** [comment]
(i updated my os)

**Comment by EragonJ** [comment]
@asdfghjkl403622 coool ! if so, i'll close this issue first ! thanks
