### ISSUE TITLE
Need an icon for Kaku

### ISSUE THREAD

**Issue by EragonJ** [EragonJ/Kaku#63]
as title.

**Comment by EragonJ** [comment]
Just asked one of my friends to work on this, will post any update here later.

**Comment by fa7ad** [comment]
Explain what kaku means in your language and maybe I can help (if not I can ask my friends as well).
_BTW, in my local language it means uncle :stuck_out_tongue:_

**Comment by EragonJ** [comment]
Well, Kaku is my girlfriend's name in Japanese. haha

**Comment by EragonJ** [comment]
For me, I just want the icon can be a girl holding earphones like this http://img11.deviantart.net/aead/i/2009/027/e/2/music_girl_by_glueboy.jpg. Because this is also a gift for her, the only request for me is making sure the icon has a girl with earphones and that's it.

**Comment by EragonJ** [comment]
The best match that I can find from Google may be this http://thumbs.dreamstime.com/z/pretty-girl-headphones-hand-drawn-illustration-vector-woman-face-profile-notes-copy-space-suitable-banner-board-poster-32797508.jpg , but because this is for icon, we can just use a rough figure to emphasize there is a girl who is right now listening to music. 

I am not good at design but I think I have done my best trying to clearly define what it looks like xD
