### ISSUE TITLE
Some "YoutubeTrack"'s in playlist are not playing after kaku restart

### ISSUE THREAD

**Issue by mimi89999** [EragonJ/Kaku#65]

**Comment by EragonJ** [comment]
Ahhh, please attach any screencast or error log, otherwise no one can't reproduce this

**Comment by EragonJ** [comment]
I haven't encountered this bug, if you have any STR or screencast for this, please feel free to reopen, thanks.

**Comment by mimi89999** [comment]
@EragonJ Create a new playlist add several songs (not from "top rankings") to that new playlist. Try to play those songs after several days... :-/

**Comment by EragonJ** [comment]
For me, they all work fine. Please attach log or STR to make it easy to debug, otherwise I have no idea about how to reproduce it and fix it.

**Comment by EragonJ** [comment]
Feel free to reopen if you have them in hand, thanks.
