### ISSUE TITLE
Something is wrong with videojs controls

### ISSUE THREAD

**Issue by mimi89999** [EragonJ/Kaku#99]
Something is wrong with videojs controls:
![capture du 2015-06-27 15 17 41](https://cloud.githubusercontent.com/assets/8530546/8392130/d74682d6-1cdf-11e5-8f2f-3cc17d237d44.png)

**Comment by EragonJ** [comment]
@mimi89999 , how do you make it happen ? Can you use inspector to check the width of player ? Take my screenshot for example, the max-width of player would be 260px and it should fit for every case. How do you make your player so small ?

![2015-06-28 10 52 02](https://cloud.githubusercontent.com/assets/68322/8396807/602b1f90-1de8-11e5-9f50-dcee642cfba0.png)

**Comment by mimi89999** [comment]
When I re-downloaded kaku and:
![capture du 2015-06-30 13 24 16](https://cloud.githubusercontent.com/assets/8530546/8428916/815cb324-1f2b-11e5-9ec1-33105eee04c6.png)

**Comment by EragonJ** [comment]
@mimi89999 , can you help to debug and see what's going on in linux build ? I am not sure why you will see two scrolling bars there and the size of window is squeezed. Please check my screenshot above and make sure they are with the same size (260px for div.left) thanks.

**Comment by mimi89999** [comment]
![capture du 2015-06-30 22 06 42](https://cloud.githubusercontent.com/assets/8530546/8439379/5ec1e93a-1f74-11e5-9eb5-ab0819e9d40a.png)

**Comment by mimi89999** [comment]
If in sidebar I set width: 260px; I get:
![capture du 2015-06-30 22 12 59](https://cloud.githubusercontent.com/assets/8530546/8439505/34cedf74-1f75-11e5-90df-287a98c01716.png)
